theory Bacon_PP_ZF_Tree_Multi_Family_Absorption
  imports
    Higher_Order_Metaphysics_PP_ZF_Classifier_Stabilization.Bacon_PP_ZF_Tree_Classifier_Stabilization
begin

section \<open>Simultaneous absorption of finitely many family probes\<close>

text \<open>
  A finite classifier-bearing component can contain several closed logical
  family builders.  Adjoining the probe generated by each builder creates a
  matrix of possible collisions: the probe generated by builder \<open>j\<close> may
  coincide with a value generated by builder \<open>i\<close>.  The following
  enlargement and characterization isolate exactly those cross-collisions.
  The result itself does not require finiteness; finiteness matters when the
  criterion is used to analyse a finite application component.
\<close>

definition pp_t_multi_family_probe_stock_enlargement ::
    "(bool list \<Rightarrow> ZF \<Rightarrow> bool) \<Rightarrow>
      ('i \<Rightarrow> oterm) \<Rightarrow> 'i set \<Rightarrow>
      bool list \<Rightarrow> ZF \<Rightarrow> bool"
where
  "pp_t_multi_family_probe_stock_enlargement S B I w X \<longleftrightarrow>
    S w X
    \<or> (\<exists>i \<in> I.
      pp_t_eqv pp_t_one_context_unary_type w
        (pp_t_family_probe_for_stock S (B i)) X)"

lemma pp_t_multi_family_probe_stock_enlargement_admissible:
  assumes B_typed:
      "\<And>i. i \<in> I \<Longrightarrow>
        [] \<turnstile> B i :
          Prop \<rightarrow>\<^sub>o pp_t_one_context_unary_type"
    and S_admissible:
      "pp_t_predicate_admissible
        pp_t_one_context_unary_type S"
  shows "pp_t_predicate_admissible
    pp_t_one_context_unary_type
    (pp_t_multi_family_probe_stock_enlargement S B I)"
  unfolding pp_t_predicate_admissible_def
proof (intro allI impI)
  fix w X Y v
  assume X: "Elem X
      (pp_t_domain pp_t_one_context_unary_type)"
    and Y: "Elem Y
      (pp_t_domain pp_t_one_context_unary_type)"
    and XY:
      "pp_t_eqv pp_t_one_context_unary_type w X Y"
    and wv: "prefix w v"
    have XY_v:
        "pp_t_eqv pp_t_one_context_unary_type v X Y"
      using pp_t_eqv_persistent[OF XY wv] .
    have YX_v:
        "pp_t_eqv pp_t_one_context_unary_type v Y X"
      using pp_t_eqv_symmetric[OF X Y XY_v] .
    have S_equiv: "S v X \<longleftrightarrow> S v Y"
      using S_admissible X Y XY wv
      unfolding pp_t_predicate_admissible_def
      by blast
    have added_equiv:
        "(\<exists>i \<in> I.
            pp_t_eqv pp_t_one_context_unary_type v
              (pp_t_family_probe_for_stock S (B i)) X)
        \<longleftrightarrow>
         (\<exists>i \<in> I.
            pp_t_eqv pp_t_one_context_unary_type v
              (pp_t_family_probe_for_stock S (B i)) Y)"
    proof
      assume left:
          "\<exists>i \<in> I.
            pp_t_eqv pp_t_one_context_unary_type v
              (pp_t_family_probe_for_stock S (B i)) X"
      then obtain i where i: "i \<in> I"
        and probe_X:
          "pp_t_eqv pp_t_one_context_unary_type v
            (pp_t_family_probe_for_stock S (B i)) X"
        by blast
      have probe:
          "Elem (pp_t_family_probe_for_stock S (B i))
            (pp_t_domain pp_t_one_context_unary_type)"
        using pp_t_family_probe_for_stock_in_domain[
          OF B_typed[OF i] S_admissible] .
      have probe_Y:
          "pp_t_eqv pp_t_one_context_unary_type v
            (pp_t_family_probe_for_stock S (B i)) Y"
        using pp_t_eqv_transitive[
          OF probe X Y probe_X XY_v] .
      show "\<exists>i \<in> I.
          pp_t_eqv pp_t_one_context_unary_type v
            (pp_t_family_probe_for_stock S (B i)) Y"
        using i probe_Y by blast
    next
      assume right:
          "\<exists>i \<in> I.
            pp_t_eqv pp_t_one_context_unary_type v
              (pp_t_family_probe_for_stock S (B i)) Y"
      then obtain i where i: "i \<in> I"
        and probe_Y:
          "pp_t_eqv pp_t_one_context_unary_type v
            (pp_t_family_probe_for_stock S (B i)) Y"
        by blast
      have probe:
          "Elem (pp_t_family_probe_for_stock S (B i))
            (pp_t_domain pp_t_one_context_unary_type)"
        using pp_t_family_probe_for_stock_in_domain[
          OF B_typed[OF i] S_admissible] .
      have probe_X:
          "pp_t_eqv pp_t_one_context_unary_type v
            (pp_t_family_probe_for_stock S (B i)) X"
        using pp_t_eqv_transitive[
          OF probe Y X probe_Y YX_v] .
      show "\<exists>i \<in> I.
          pp_t_eqv pp_t_one_context_unary_type v
            (pp_t_family_probe_for_stock S (B i)) X"
        using i probe_X by blast
    qed
  show "pp_t_multi_family_probe_stock_enlargement S B I v X
      \<longleftrightarrow>
    pp_t_multi_family_probe_stock_enlargement S B I v Y"
    unfolding pp_t_multi_family_probe_stock_enlargement_def
    using S_equiv added_equiv by blast
qed

lemma pp_t_multi_family_generated_value_membership_iff:
  "pp_t_multi_family_probe_stock_enlargement S B I w
      (pp_t_closed_den (B i) \<acute> p)
    \<longleftrightarrow>
    S w (pp_t_closed_den (B i) \<acute> p)
    \<or> (\<exists>j \<in> I.
      pp_t_eqv pp_t_one_context_unary_type w
        (pp_t_family_probe_for_stock S (B j))
        (pp_t_closed_den (B i) \<acute> p))"
  unfolding pp_t_multi_family_probe_stock_enlargement_def
  by simp

(*
  Continued in the child session
  Bacon_PP_ZF_Tree_Multi_Family_Collision_Characterization, after splitting
  the two directions between the necessity and sufficiency sessions.

theorem pp_t_one_of_multi_family_probes_stabilizes_iff_cross_collisions_absorbed:
  assumes i: "i \<in> I"
    and B_typed:
      "\<And>j. j \<in> I \<Longrightarrow>
        [] \<turnstile> B j :
          Prop \<rightarrow>\<^sub>o pp_t_one_context_unary_type"
    and S_admissible:
      "pp_t_predicate_admissible
        pp_t_one_context_unary_type S"
  shows
    "pp_t_family_probe_for_stock
        (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
      = pp_t_family_probe_for_stock S (B i)
    \<longleftrightarrow>
    (\<forall>p w.
      Elem p (pp_t_domain Prop)
      \<longrightarrow>
      (\<exists>j \<in> I.
        pp_t_eqv pp_t_one_context_unary_type w
          (pp_t_family_probe_for_stock S (B j))
          (pp_t_closed_den (B i) \<acute> p))
      \<longrightarrow>
      S w (pp_t_closed_den (B i) \<acute> p))"
proof
  assume stable:
      "pp_t_family_probe_for_stock
          (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
        = pp_t_family_probe_for_stock S (B i)"
  show "\<forall>p w.
      Elem p (pp_t_domain Prop)
      \<longrightarrow>
      (\<exists>j \<in> I.
        pp_t_eqv pp_t_one_context_unary_type w
          (pp_t_family_probe_for_stock S (B j))
          (pp_t_closed_den (B i) \<acute> p))
      \<longrightarrow>
      S w (pp_t_closed_den (B i) \<acute> p)"
  proof (intro allI impI)
    fix p w
    assume p: "Elem p (pp_t_domain Prop)"
      and collision:
        "\<exists>j \<in> I.
          pp_t_eqv pp_t_one_context_unary_type w
            (pp_t_family_probe_for_stock S (B j))
            (pp_t_closed_den (B i) \<acute> p)"
    have enlarged_member:
        "pp_t_multi_family_probe_stock_enlargement S B I w
          (pp_t_closed_den (B i) \<acute> p)"
      using collision
      unfolding pp_t_multi_family_probe_stock_enlargement_def
      by blast
    have reevaluated_true:
        "pp_t_holds
          (pp_t_family_probe_for_stock
            (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
            \<acute> p) w"
      using pp_t_family_probe_for_stock_apply_holds[
        OF B_typed[OF i]
          pp_t_multi_family_probe_stock_enlargement_admissible[
            OF B_typed S_admissible]
          p,
        of w]
        enlarged_member by blast
    have old_true:
        "pp_t_holds
          (pp_t_family_probe_for_stock S (B i) \<acute> p) w"
      using reevaluated_true unfolding stable .
    show "S w (pp_t_closed_den (B i) \<acute> p)"
      using pp_t_family_probe_for_stock_apply_holds[
        OF B_typed[OF i] S_admissible p, of w]
        old_true by blast
  qed
next
  assume absorbed:
      "\<forall>p w.
        Elem p (pp_t_domain Prop)
        \<longrightarrow>
        (\<exists>j \<in> I.
          pp_t_eqv pp_t_one_context_unary_type w
            (pp_t_family_probe_for_stock S (B j))
            (pp_t_closed_den (B i) \<acute> p))
        \<longrightarrow>
        S w (pp_t_closed_den (B i) \<acute> p)"
  show "pp_t_family_probe_for_stock
        (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
      = pp_t_family_probe_for_stock S (B i)"
  proof (rule pp_t_unary_function_ext)
    show "Elem
        (pp_t_family_probe_for_stock
          (pp_t_multi_family_probe_stock_enlargement S B I) (B i))
        (pp_t_domain pp_t_one_context_unary_type)"
      using pp_t_family_probe_for_stock_in_domain[
        OF B_typed[OF i]
          pp_t_multi_family_probe_stock_enlargement_admissible[
            OF B_typed S_admissible]] .
    show "Elem (pp_t_family_probe_for_stock S (B i))
        (pp_t_domain pp_t_one_context_unary_type)"
      using pp_t_family_probe_for_stock_in_domain[
        OF B_typed[OF i] S_admissible] .
    fix p
    assume p: "Elem p (pp_t_domain Prop)"
    show "pp_t_family_probe_for_stock
          (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
          \<acute> p
        = pp_t_family_probe_for_stock S (B i) \<acute> p"
    proof (rule pp_t_prop_ext)
      show "Elem
          (pp_t_family_probe_for_stock
            (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
            \<acute> p)
          (pp_t_domain Prop)"
        using pp_t_app_closed[
          OF pp_t_family_probe_for_stock_in_domain[
            OF B_typed[OF i]
              pp_t_multi_family_probe_stock_enlargement_admissible[
                OF B_typed S_admissible]]
            p] .
      show "Elem
          (pp_t_family_probe_for_stock S (B i) \<acute> p)
          (pp_t_domain Prop)"
        using pp_t_app_closed[
          OF pp_t_family_probe_for_stock_in_domain[
            OF B_typed[OF i] S_admissible] p] .
      fix w
      have enlarged:
          "pp_t_holds
            (pp_t_family_probe_for_stock
              (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
              \<acute> p) w
          \<longleftrightarrow>
          pp_t_multi_family_probe_stock_enlargement S B I w
            (pp_t_closed_den (B i) \<acute> p)"
        using pp_t_family_probe_for_stock_apply_holds[
          OF B_typed[OF i]
            pp_t_multi_family_probe_stock_enlargement_admissible[
              OF B_typed S_admissible]
            p,
          of w] .
      have old:
          "pp_t_holds
            (pp_t_family_probe_for_stock S (B i) \<acute> p) w
          \<longleftrightarrow>
          S w (pp_t_closed_den (B i) \<acute> p)"
        using pp_t_family_probe_for_stock_apply_holds[
          OF B_typed[OF i] S_admissible p, of w] .
      show "pp_t_holds
            (pp_t_family_probe_for_stock
              (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
              \<acute> p) w
        \<longleftrightarrow>
        pp_t_holds
          (pp_t_family_probe_for_stock S (B i) \<acute> p) w"
        using enlarged old absorbed[rule_format, OF p, of w]
        unfolding pp_t_multi_family_probe_stock_enlargement_def
        by blast
    qed
  qed
qed

theorem pp_t_multi_family_probes_stabilize_iff_cross_collision_matrix_absorbed:
  assumes B_typed:
      "\<And>i. i \<in> I \<Longrightarrow>
        [] \<turnstile> B i :
          Prop \<rightarrow>\<^sub>o pp_t_one_context_unary_type"
    and S_admissible:
      "pp_t_predicate_admissible
        pp_t_one_context_unary_type S"
  shows
    "(\<forall>i \<in> I.
      pp_t_family_probe_for_stock
          (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
        = pp_t_family_probe_for_stock S (B i))
    \<longleftrightarrow>
    (\<forall>i \<in> I. \<forall>p w.
      Elem p (pp_t_domain Prop)
      \<longrightarrow>
      (\<exists>j \<in> I.
        pp_t_eqv pp_t_one_context_unary_type w
          (pp_t_family_probe_for_stock S (B j))
          (pp_t_closed_den (B i) \<acute> p))
      \<longrightarrow>
      S w (pp_t_closed_den (B i) \<acute> p))"
  using pp_t_one_of_multi_family_probes_stabilizes_iff_cross_collisions_absorbed[
    OF _ B_typed S_admissible]
  by blast
*)

(*
  Continued in the child session
  Bacon_PP_ZF_Tree_Multi_Family_Off_Diagonal.

theorem pp_t_diagonally_reflexive_multi_family_probes_stabilize_iff_off_diagonal_collisions_absorbed:
  assumes B_typed:
      "\<And>i. i \<in> I \<Longrightarrow>
        [] \<turnstile> B i :
          Prop \<rightarrow>\<^sub>o pp_t_one_context_unary_type"
    and S_admissible:
      "pp_t_predicate_admissible
        pp_t_one_context_unary_type S"
    and diagonal:
      "\<And>i p w.
        i \<in> I \<Longrightarrow>
        Elem p (pp_t_domain Prop) \<Longrightarrow>
        pp_t_holds
          ((pp_t_closed_den (B i) \<acute> p) \<acute> p) w"
  shows
    "(\<forall>i \<in> I.
      pp_t_family_probe_for_stock
          (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
        = pp_t_family_probe_for_stock S (B i))
    \<longleftrightarrow>
    (\<forall>i \<in> I. \<forall>j \<in> I. \<forall>p w.
      j \<noteq> i
      \<longrightarrow>
      Elem p (pp_t_domain Prop)
      \<longrightarrow>
      pp_t_eqv pp_t_one_context_unary_type w
        (pp_t_family_probe_for_stock S (B j))
        (pp_t_closed_den (B i) \<acute> p)
      \<longrightarrow>
      S w (pp_t_closed_den (B i) \<acute> p))"
proof
  assume stable:
      "\<forall>i \<in> I.
        pp_t_family_probe_for_stock
            (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
          = pp_t_family_probe_for_stock S (B i)"
  have all_collisions:
      "\<forall>i \<in> I. \<forall>p w.
        Elem p (pp_t_domain Prop)
        \<longrightarrow>
        (\<exists>j \<in> I.
          pp_t_eqv pp_t_one_context_unary_type w
            (pp_t_family_probe_for_stock S (B j))
            (pp_t_closed_den (B i) \<acute> p))
        \<longrightarrow>
        S w (pp_t_closed_den (B i) \<acute> p)"
    using pp_t_multi_family_probes_stabilize_iff_cross_collision_matrix_absorbed[
      OF B_typed S_admissible]
      stable by blast
  show "\<forall>i \<in> I. \<forall>j \<in> I. \<forall>p w.
      j \<noteq> i
      \<longrightarrow>
      Elem p (pp_t_domain Prop)
      \<longrightarrow>
      pp_t_eqv pp_t_one_context_unary_type w
        (pp_t_family_probe_for_stock S (B j))
        (pp_t_closed_den (B i) \<acute> p)
      \<longrightarrow>
      S w (pp_t_closed_den (B i) \<acute> p)"
    using all_collisions by blast
next
  assume off_diagonal:
      "\<forall>i \<in> I. \<forall>j \<in> I. \<forall>p w.
        j \<noteq> i
        \<longrightarrow>
        Elem p (pp_t_domain Prop)
        \<longrightarrow>
        pp_t_eqv pp_t_one_context_unary_type w
          (pp_t_family_probe_for_stock S (B j))
          (pp_t_closed_den (B i) \<acute> p)
        \<longrightarrow>
        S w (pp_t_closed_den (B i) \<acute> p)"
  have all_collisions:
      "\<forall>i \<in> I. \<forall>p w.
        Elem p (pp_t_domain Prop)
        \<longrightarrow>
        (\<exists>j \<in> I.
          pp_t_eqv pp_t_one_context_unary_type w
            (pp_t_family_probe_for_stock S (B j))
            (pp_t_closed_den (B i) \<acute> p))
        \<longrightarrow>
        S w (pp_t_closed_den (B i) \<acute> p)"
  proof (intro ballI allI impI)
    fix i p w
    assume i: "i \<in> I"
      and p: "Elem p (pp_t_domain Prop)"
      and some_collision:
        "\<exists>j \<in> I.
          pp_t_eqv pp_t_one_context_unary_type w
            (pp_t_family_probe_for_stock S (B j))
            (pp_t_closed_den (B i) \<acute> p)"
    then obtain j where j: "j \<in> I"
      and collision:
        "pp_t_eqv pp_t_one_context_unary_type w
          (pp_t_family_probe_for_stock S (B j))
          (pp_t_closed_den (B i) \<acute> p)"
      by blast
    show "S w (pp_t_closed_den (B i) \<acute> p)"
    proof (cases "j = i")
      case True
      show ?thesis
        using pp_t_family_probe_collision_absorbed[
          OF B_typed[OF i] S_admissible
            diagonal[OF i] p,
          of w]
          collision
        unfolding True by blast
    next
      case False
      show ?thesis
        using off_diagonal i j False p collision by blast
    qed
  qed
  show "\<forall>i \<in> I.
      pp_t_family_probe_for_stock
          (pp_t_multi_family_probe_stock_enlargement S B I) (B i)
        = pp_t_family_probe_for_stock S (B i)"
    using pp_t_multi_family_probes_stabilize_iff_cross_collision_matrix_absorbed[
      OF B_typed S_admissible]
      all_collisions by blast
qed
*)

end
