theory Bacon_PP_ZF_Tree_Range_Term_Basis
  imports Bacon_PP_ZF_Tree_Range_Diagonal
begin

section \<open>The applicative term basis generated by one enumerator\<close>

datatype pp_t_basis_expr =
    PPLogical oterm
  | PPInd nat
  | PPEnumerator
  | PPApply pp_t_basis_expr pp_t_basis_expr

instantiation pp_t_basis_expr :: countable
begin

instance
  by countable_datatype

end

lemma pp_t_basis_expr_UNIV_countable:
  "countable (UNIV :: pp_t_basis_expr set)"
  by simp

fun pp_t_basis_expr_type ::
    "pp_t_basis_expr \<Rightarrow> otype option"
where
  "pp_t_basis_expr_type (PPLogical M) =
    (if pp_logical_vocabulary M
     then infer_type [] M
     else None)"
| "pp_t_basis_expr_type (PPInd n) = Some Ind"
| "pp_t_basis_expr_type PPEnumerator =
    Some (Ind \<rightarrow>\<^sub>o pp_t_unary_type)"
| "pp_t_basis_expr_type (PPApply F X) =
    (case pp_t_basis_expr_type F of
      Some (\<sigma> \<rightarrow>\<^sub>o \<tau>) =>
        (if pp_t_basis_expr_type X = Some \<sigma>
         then Some \<tau> else None)
    | _ => None)"

fun pp_t_basis_expr_den ::
    "ZF \<Rightarrow> pp_t_basis_expr \<Rightarrow> ZF"
where
  "pp_t_basis_expr_den E (PPLogical M) = pp_t_closed_den M"
| "pp_t_basis_expr_den E (PPInd n) = nat2Nat n"
| "pp_t_basis_expr_den E PPEnumerator = E"
| "pp_t_basis_expr_den E (PPApply F X) =
    pp_t_basis_expr_den E F \<acute> pp_t_basis_expr_den E X"

definition pp_t_enumerator_basis ::
    "ZF \<Rightarrow> otype \<Rightarrow> ZF set"
where
  "pp_t_enumerator_basis E \<sigma> =
    pp_t_basis_expr_den E `
      {T. pp_t_basis_expr_type T = Some \<sigma>}"

lemma pp_t_basis_expr_den_typed:
  assumes E:
      "Elem E
        (pp_t_domain (Ind \<rightarrow>\<^sub>o pp_t_unary_type))"
    and T: "pp_t_basis_expr_type T = Some \<sigma>"
  shows "Elem (pp_t_basis_expr_den E T) (pp_t_domain \<sigma>)"
  using T
proof (induction T arbitrary: \<sigma>)
  case (PPLogical M)
  then have logical: "pp_logical_vocabulary M"
    and inferred: "infer_type [] M = Some \<sigma>"
    by (auto split: if_splits)
  have typed: "[] \<turnstile> M : \<sigma>"
    using infer_type_sound[OF inferred] .
  show ?case
    using pp_t_closed_den_in_domain[OF typed] by simp
next
  case (PPInd n)
  then have "\<sigma> = Ind" by simp
  then show ?case by (simp add: Elem_nat2Nat_Nat)
next
  case PPEnumerator
  then have
      "\<sigma> = (Ind \<rightarrow>\<^sub>o pp_t_unary_type)"
    by simp
  then show ?case using E by simp
next
  case (PPApply F X)
  then obtain \<alpha> \<beta> where
      F_type: "pp_t_basis_expr_type F =
        Some (\<alpha> \<rightarrow>\<^sub>o \<beta>)"
    and X_type: "pp_t_basis_expr_type X = Some \<alpha>"
    and sigma: "\<sigma> = \<beta>"
    by (auto split: option.splits otype.splits if_splits)
  have F_den:
      "Elem (pp_t_basis_expr_den E F)
        (pp_t_domain (\<alpha> \<rightarrow>\<^sub>o \<beta>))"
    using PPApply.IH(1)[OF F_type] .
  have X_den:
      "Elem (pp_t_basis_expr_den E X) (pp_t_domain \<alpha>)"
    using PPApply.IH(2)[OF X_type] .
  show ?case
    unfolding sigma pp_t_basis_expr_den.simps
    using pp_t_app_closed[OF F_den X_den] .
qed

lemma pp_t_basis_expr_den_cone_natural:
  assumes E:
      "Elem E
        (pp_t_domain (Ind \<rightarrow>\<^sub>o pp_t_unary_type))"
    and E_cone:
      "\<And>s. pp_t_cone_rel
        (Ind \<rightarrow>\<^sub>o pp_t_unary_type) s E E"
    and T: "pp_t_basis_expr_type T = Some \<sigma>"
  shows "pp_t_cone_rel \<sigma> s
    (pp_t_basis_expr_den E T) (pp_t_basis_expr_den E T)"
  using T
proof (induction T arbitrary: \<sigma>)
  case (PPLogical M)
  then have logical: "pp_logical_vocabulary M"
    and inferred: "infer_type [] M = Some \<sigma>"
    by (auto split: if_splits)
  have typed: "[] \<turnstile> M : \<sigma>"
    using infer_type_sound[OF inferred] .
  show ?case
    using UnconditionalCone.pp_t_closed_logical_den_cone_related[
      OF typed logical] by simp
next
  case (PPInd n)
  then show ?case by simp
next
  case PPEnumerator
  then show ?case using E_cone[of s] by simp
next
  case (PPApply F X)
  then obtain \<alpha> \<beta> where
      F_type: "pp_t_basis_expr_type F =
        Some (\<alpha> \<rightarrow>\<^sub>o \<beta>)"
    and X_type: "pp_t_basis_expr_type X = Some \<alpha>"
    and sigma: "\<sigma> = \<beta>"
    by (auto split: option.splits otype.splits if_splits)
  have F_rel:
      "pp_t_cone_rel (\<alpha> \<rightarrow>\<^sub>o \<beta>) s
        (pp_t_basis_expr_den E F) (pp_t_basis_expr_den E F)"
    using PPApply.IH(1)[OF F_type] .
  have X_rel:
      "pp_t_cone_rel \<alpha> s
        (pp_t_basis_expr_den E X) (pp_t_basis_expr_den E X)"
    using PPApply.IH(2)[OF X_type] .
  have X_den:
      "Elem (pp_t_basis_expr_den E X) (pp_t_domain \<alpha>)"
    using pp_t_basis_expr_den_typed[OF E X_type] .
  show ?case
    unfolding sigma pp_t_basis_expr_den.simps
    using F_rel X_den X_den X_rel by simp
qed

lemma pp_t_enumerator_basis_countable:
  "countable (pp_t_enumerator_basis E \<sigma>)"
proof -
  have expressions:
      "countable {T. pp_t_basis_expr_type T = Some \<sigma>}"
    by simp
  show ?thesis
    unfolding pp_t_enumerator_basis_def
    using expressions by (rule countable_image)
qed

lemma pp_t_enumerator_basis_typed:
  assumes E:
      "Elem E
        (pp_t_domain (Ind \<rightarrow>\<^sub>o pp_t_unary_type))"
    and x: "x \<in> pp_t_enumerator_basis E \<sigma>"
  shows "Elem x (pp_t_domain \<sigma>)"
proof -
  obtain T where
      T: "pp_t_basis_expr_type T = Some \<sigma>"
    and x_def: "x = pp_t_basis_expr_den E T"
    using x unfolding pp_t_enumerator_basis_def by blast
  show ?thesis
    unfolding x_def
    using pp_t_basis_expr_den_typed[OF E T] .
qed

lemma pp_t_enumerator_basis_cone_natural:
  assumes E:
      "Elem E
        (pp_t_domain (Ind \<rightarrow>\<^sub>o pp_t_unary_type))"
    and E_cone:
      "\<And>s. pp_t_cone_rel
        (Ind \<rightarrow>\<^sub>o pp_t_unary_type) s E E"
    and x: "x \<in> pp_t_enumerator_basis E \<sigma>"
  shows "pp_t_cone_rel \<sigma> s x x"
proof -
  obtain T where
      T: "pp_t_basis_expr_type T = Some \<sigma>"
    and x_def: "x = pp_t_basis_expr_den E T"
    using x unfolding pp_t_enumerator_basis_def by blast
  show ?thesis
    unfolding x_def
    using pp_t_basis_expr_den_cone_natural[
      OF E E_cone T] .
qed

lemma pp_t_enumerator_basis_contains_logical:
  assumes typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  shows "pp_t_closed_den M \<in> pp_t_enumerator_basis E \<sigma>"
proof -
  have inferred: "infer_type [] M = Some \<sigma>"
    using infer_type_complete[OF typed] .
  have expression:
      "pp_t_basis_expr_type (PPLogical M) = Some \<sigma>"
    using logical inferred by simp
  show ?thesis
    unfolding pp_t_enumerator_basis_def
  proof (rule image_eqI[where x="PPLogical M"])
    show "pp_t_closed_den M =
        pp_t_basis_expr_den E (PPLogical M)"
      by simp
    show "PPLogical M \<in>
        {T. pp_t_basis_expr_type T = Some \<sigma>}"
      using expression by simp
  qed
qed

lemma pp_t_enumerator_basis_contains_ind:
  assumes n: "Elem n (pp_t_domain Ind)"
  shows "n \<in> pp_t_enumerator_basis E Ind"
proof -
  have n_rep: "nat2Nat (Nat2nat n) = n"
    using n by simp
  have expression:
      "pp_t_basis_expr_type (PPInd (Nat2nat n)) = Some Ind"
    by simp
  show ?thesis
    unfolding pp_t_enumerator_basis_def
  proof (rule image_eqI[where x="PPInd (Nat2nat n)"])
    show "n = pp_t_basis_expr_den E (PPInd (Nat2nat n))"
      using n_rep by simp
    show "PPInd (Nat2nat n) \<in>
        {T. pp_t_basis_expr_type T = Some Ind}"
      using expression by simp
  qed
qed

lemma pp_t_enumerator_basis_contains_enumerator:
  "E \<in> pp_t_enumerator_basis E
    (Ind \<rightarrow>\<^sub>o pp_t_unary_type)"
  unfolding pp_t_enumerator_basis_def
proof (rule image_eqI[where x=PPEnumerator])
  show "E = pp_t_basis_expr_den E PPEnumerator"
    by simp
  show "PPEnumerator \<in>
      {T. pp_t_basis_expr_type T =
        Some (Ind \<rightarrow>\<^sub>o pp_t_unary_type)}"
    by simp
qed

lemma pp_t_enumerator_basis_application:
  assumes f:
      "f \<in> pp_t_enumerator_basis E
        (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    and x: "x \<in> pp_t_enumerator_basis E \<sigma>"
  shows "f \<acute> x \<in> pp_t_enumerator_basis E \<tau>"
proof -
  obtain F where
      F_type:
        "pp_t_basis_expr_type F =
          Some (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    and f_def: "f = pp_t_basis_expr_den E F"
    using f unfolding pp_t_enumerator_basis_def by blast
  obtain X where X_type: "pp_t_basis_expr_type X = Some \<sigma>"
    and x_def: "x = pp_t_basis_expr_den E X"
    using x unfolding pp_t_enumerator_basis_def by blast
  have application:
      "pp_t_basis_expr_type (PPApply F X) = Some \<tau>"
    using F_type X_type by simp
  show ?thesis
    unfolding pp_t_enumerator_basis_def f_def x_def
  proof (rule image_eqI[where x="PPApply F X"])
    show "pp_t_basis_expr_den E F \<acute> pp_t_basis_expr_den E X =
        pp_t_basis_expr_den E (PPApply F X)"
      by simp
    show "PPApply F X \<in>
        {T. pp_t_basis_expr_type T = Some \<tau>}"
      using application by simp
  qed
qed

locale pp_t_cone_natural_enumerator =
  fixes E :: ZF
  assumes E_typed:
      "Elem E
        (pp_t_domain (Ind \<rightarrow>\<^sub>o pp_t_unary_type))"
    and E_cone_natural:
      "\<And>s. pp_t_cone_rel
        (Ind \<rightarrow>\<^sub>o pp_t_unary_type) s E E"
begin

sublocale TermBasis:
  pp_t_stock_basis "pp_t_enumerator_basis E"
proof
  fix \<sigma> d
  assume d: "d \<in> pp_t_enumerator_basis E \<sigma>"
  show "Elem d (pp_t_domain \<sigma>)"
    using pp_t_enumerator_basis_typed[OF E_typed d] .
next
  fix \<sigma>
  show "countable (pp_t_enumerator_basis E \<sigma>)"
    by (rule pp_t_enumerator_basis_countable)
next
  fix \<sigma> d s
  assume d: "d \<in> pp_t_enumerator_basis E \<sigma>"
  show "pp_t_cone_rel \<sigma> s d d"
    using pp_t_enumerator_basis_cone_natural[
      OF E_typed E_cone_natural d] .
next
  fix \<sigma> M
  assume typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  show "pp_t_closed_den M \<in> pp_t_enumerator_basis E \<sigma>"
    using pp_t_enumerator_basis_contains_logical[
      OF typed logical] .
next
  fix \<sigma> \<tau> f x
  assume f:
      "f \<in> pp_t_enumerator_basis E
        (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    and x: "x \<in> pp_t_enumerator_basis E \<sigma>"
  have application:
      "f \<acute> x \<in> pp_t_enumerator_basis E \<tau>"
    using pp_t_enumerator_basis_application[OF f x] .
  have typed:
      "Elem (f \<acute> x) (pp_t_domain \<tau>)"
    using pp_t_enumerator_basis_typed[
      OF E_typed application] .
  have reflexive:
      "pp_t_eqv \<tau> [] (f \<acute> x) (f \<acute> x)"
    using pp_t_eqv_reflexive[OF typed] .
  show "\<exists>d \<in> pp_t_enumerator_basis E \<tau>.
      pp_t_eqv \<tau> [] (f \<acute> x) d"
    using application reflexive by blast
qed

lemma pp_t_enumerator_in_term_basis_stock:
  "pp_t_basis_stock (pp_t_enumerator_basis E)
    (Ind \<rightarrow>\<^sub>o pp_t_unary_type) [] E"
  using TermBasis.pp_t_basis_member_in_stock[
    OF pp_t_enumerator_basis_contains_enumerator] .

lemma pp_t_all_ind_in_term_basis:
  assumes n: "Elem n (pp_t_domain Ind)"
  shows "n \<in> pp_t_enumerator_basis E Ind"
  using pp_t_enumerator_basis_contains_ind[OF n] .

theorem pp_t_term_basis_range_complete_iff_fixed_point:
  "(\<forall>w X.
      pp_t_basis_stock (pp_t_enumerator_basis E)
        pp_t_unary_type w X
      \<longleftrightarrow>
      pp_t_range_stock E w X)
    \<longleftrightarrow>
    pp_t_enumerator_basis E pp_t_unary_type =
      (\<lambda>n. E \<acute> n) `
        {n. Elem n (pp_t_domain Ind)}"
  using TermBasis.pp_t_range_complete_all_worlds_iff_exact_range[
    OF E_typed] .

theorem pp_t_term_basis_self_classifies_from_fixed_point:
  assumes fixed_point:
      "pp_t_enumerator_basis E pp_t_unary_type =
        (\<lambda>n. E \<acute> n) `
          {n. Elem n (pp_t_domain Ind)}"
  shows "pp_t_basis_stock (pp_t_enumerator_basis E)
    (pp_t_unary_type \<rightarrow>\<^sub>o Prop) []
    (pp_t_classifier pp_t_unary_type
      (pp_t_basis_stock (pp_t_enumerator_basis E)
        pp_t_unary_type))"
proof -
  have range_complete:
      "\<And>w X.
        pp_t_basis_stock (pp_t_enumerator_basis E)
          pp_t_unary_type w X
        \<longleftrightarrow>
        pp_t_range_stock E w X"
    using pp_t_term_basis_range_complete_iff_fixed_point
      fixed_point by blast
  show ?thesis
    using TermBasis.pp_t_range_complete_basis_self_classifies[
      OF pp_t_enumerator_in_term_basis_stock range_complete] .
qed

end

end
