theory Bacon_PP_ZF_Goodman_L2_Composition_Fragment
  imports Bacon_PP_ZF_Goodman_L2_Global_Reduction
begin

section \<open>The composition fragment generated by negation, necessity, and possibility\<close>

text \<open>
  The preceding reduction excludes every operator that begins with necessity
  or possibility.  Negation can conceal that form syntactically.  We therefore
  first prove that a reversible prefix neither creates nor destroys
  right-cancellativity.  This removes negation and, more generally, every
  reversible closed logical prefix from the remaining negative search.
\<close>

lemma pp_b_exact_right_cancellative_reversible_prefix:
  assumes K: "K \<in> pp_b_exact_G"
    and X: "X \<in> pp_b_exact_stock"
  shows "pp_b_exact_right_cancellative (K \<circ> X) \<longleftrightarrow>
    pp_b_exact_right_cancellative X"
proof -
  obtain Ki where K_stock: "K \<in> pp_b_exact_stock"
    and Ki_stock: "Ki \<in> pp_b_exact_stock"
    and KKi: "K \<circ> Ki = id"
    and KiK: "Ki \<circ> K = id"
    using K by (rule pp_b_exact_GE)
  show ?thesis
  proof
    assume prefixed:
        "pp_b_exact_right_cancellative (K \<circ> X)"
    show "pp_b_exact_right_cancellative X"
    proof (unfold pp_b_exact_right_cancellative_def,
        intro ballI impI)
      fix A B
      assume A: "A \<in> pp_b_exact_stock"
        and B: "B \<in> pp_b_exact_stock"
        and AX_BX: "A \<circ> X = B \<circ> X"
      have AKi: "A \<circ> Ki \<in> pp_b_exact_stock"
        using A Ki_stock by (rule pp_b_exact_stock_compose)
      have BKi: "B \<circ> Ki \<in> pp_b_exact_stock"
        using B Ki_stock by (rule pp_b_exact_stock_compose)
      have prefixed_equality:
          "(A \<circ> Ki) \<circ> (K \<circ> X) =
           (B \<circ> Ki) \<circ> (K \<circ> X)"
      proof (rule ext)
        fix p
        have inverse_at_X:
            "Ki (K (X p)) = X p"
          using fun_cong[OF KiK, of "X p"] by simp
        have equality_at_p: "A (X p) = B (X p)"
          using fun_cong[OF AX_BX, of p] by simp
        show "((A \<circ> Ki) \<circ> (K \<circ> X)) p =
            ((B \<circ> Ki) \<circ> (K \<circ> X)) p"
          using inverse_at_X equality_at_p by simp
      qed
      have AKi_BKi: "A \<circ> Ki = B \<circ> Ki"
        using prefixed AKi BKi prefixed_equality
        unfolding pp_b_exact_right_cancellative_def by blast
      show "A = B"
      proof (rule ext)
        fix p
        have inverse_at_p: "Ki (K p) = p"
          using fun_cong[OF KiK, of p] by simp
        have equality_at_Kp: "A (Ki (K p)) = B (Ki (K p))"
          using fun_cong[OF AKi_BKi, of "K p"] by simp
        show "A p = B p"
          using inverse_at_p equality_at_Kp by simp
      qed
    qed
  next
    assume unprefixed: "pp_b_exact_right_cancellative X"
    show "pp_b_exact_right_cancellative (K \<circ> X)"
    proof (unfold pp_b_exact_right_cancellative_def,
        intro ballI impI)
      fix A B
      assume A: "A \<in> pp_b_exact_stock"
        and B: "B \<in> pp_b_exact_stock"
        and AKX_BKX:
          "A \<circ> (K \<circ> X) = B \<circ> (K \<circ> X)"
      have AK: "A \<circ> K \<in> pp_b_exact_stock"
        using A K_stock by (rule pp_b_exact_stock_compose)
      have BK: "B \<circ> K \<in> pp_b_exact_stock"
        using B K_stock by (rule pp_b_exact_stock_compose)
      have "(A \<circ> K) \<circ> X = (B \<circ> K) \<circ> X"
        using AKX_BKX by (simp add: fun_eq_iff)
      then have AK_BK: "A \<circ> K = B \<circ> K"
        using unprefixed AK BK
        unfolding pp_b_exact_right_cancellative_def by blast
      show "A = B"
      proof (rule ext)
        fix p
        have inverse_at_p: "K (Ki p) = p"
          using fun_cong[OF KKi, of p] by simp
        have equality_at_Kip: "A (K (Ki p)) = B (K (Ki p))"
          using fun_cong[OF AK_BK, of "Ki p"] by simp
        show "A p = B p"
          using inverse_at_p equality_at_Kip by simp
      qed
    qed
  qed
qed

corollary pp_b_exact_reversible_right_cancellative:
  assumes "K \<in> pp_b_exact_G"
  shows "pp_b_exact_right_cancellative K"
proof -
  have id_stock: "id \<in> pp_b_exact_stock"
    by (rule pp_b_exact_base_operators(1))
  have "pp_b_exact_right_cancellative (K \<circ> id) \<longleftrightarrow>
      pp_b_exact_right_cancellative id"
    using assms id_stock
    by (rule pp_b_exact_right_cancellative_reversible_prefix)
  then show ?thesis
    using pp_b_exact_identity_right_cancellative by simp
qed

definition pp_b_exact_modally_factorable ::
    "pp_b_operator \<Rightarrow> bool" where
  "pp_b_exact_modally_factorable Z \<longleftrightarrow>
    (\<exists>K \<in> pp_b_exact_G.
      \<exists>H \<in> pp_b_exact_stock.
        Z = K \<circ> (pp_b_box \<circ> H) \<or>
        Z = K \<circ> (pp_b_diamond \<circ> H))"

lemma pp_b_exact_modally_factorable_stock:
  assumes "pp_b_exact_modally_factorable Z"
  shows "Z \<in> pp_b_exact_stock"
proof -
  obtain K H where K: "K \<in> pp_b_exact_G"
    and H: "H \<in> pp_b_exact_stock"
    and factor:
      "Z = K \<circ> (pp_b_box \<circ> H) \<or>
       Z = K \<circ> (pp_b_diamond \<circ> H)"
    using assms unfolding pp_b_exact_modally_factorable_def
    by blast
  have K_stock: "K \<in> pp_b_exact_stock"
    using K by (rule pp_b_exact_GE)
  have box_H: "pp_b_box \<circ> H \<in> pp_b_exact_stock"
    using pp_b_exact_base_operators(4) H
    by (rule pp_b_exact_stock_compose)
  have diamond_H: "pp_b_diamond \<circ> H \<in> pp_b_exact_stock"
    using pp_b_exact_base_operators(5) H
    by (rule pp_b_exact_stock_compose)
  show ?thesis
    using factor
      pp_b_exact_stock_compose[OF K_stock box_H]
      pp_b_exact_stock_compose[OF K_stock diamond_H]
    by blast
qed

theorem pp_b_exact_modally_factorable_not_right_cancellative:
  assumes factorable: "pp_b_exact_modally_factorable Z"
  shows "\<not> pp_b_exact_right_cancellative Z"
proof -
  obtain K H where K: "K \<in> pp_b_exact_G"
    and H: "H \<in> pp_b_exact_stock"
    and factor:
      "Z = K \<circ> (pp_b_box \<circ> H) \<or>
       Z = K \<circ> (pp_b_diamond \<circ> H)"
    using factorable unfolding pp_b_exact_modally_factorable_def
    by blast
  have box_H: "pp_b_box \<circ> H \<in> pp_b_exact_stock"
    using pp_b_exact_base_operators(4) H
    by (rule pp_b_exact_stock_compose)
  have diamond_H: "pp_b_diamond \<circ> H \<in> pp_b_exact_stock"
    using pp_b_exact_base_operators(5) H
    by (rule pp_b_exact_stock_compose)
  have box_not:
      "\<not> pp_b_exact_right_cancellative
        (K \<circ> (pp_b_box \<circ> H))"
    using
      pp_b_exact_right_cancellative_reversible_prefix[OF K box_H]
      pp_b_exact_box_left_composition_not_right_cancellative[OF H]
    by blast
  have diamond_not:
      "\<not> pp_b_exact_right_cancellative
        (K \<circ> (pp_b_diamond \<circ> H))"
    using
      pp_b_exact_right_cancellative_reversible_prefix[OF K diamond_H]
      pp_b_exact_diamond_left_composition_not_right_cancellative[OF H]
    by blast
  show ?thesis
    using factor box_not diamond_not by blast
qed

corollary pp_b_exact_right_cancellative_not_modally_factorable:
  assumes "pp_b_exact_right_cancellative Z"
  shows "\<not> pp_b_exact_modally_factorable Z"
  using assms pp_b_exact_modally_factorable_not_right_cancellative
  by blast

text \<open>
  We can state the resulting normalization for the whole composition fragment
  without assuming that this fragment exhausts the complete closed logical
  stock.  It is generated by identity under left composition with negation,
  necessity, and possibility.
\<close>

inductive pp_b_exact_modal_composition_word ::
    "pp_b_operator \<Rightarrow> bool" where
  identity:
    "pp_b_exact_modal_composition_word id"
| complement:
    "pp_b_exact_modal_composition_word X \<Longrightarrow>
     pp_b_exact_modal_composition_word (pp_b_complement \<circ> X)"
| box:
    "pp_b_exact_modal_composition_word X \<Longrightarrow>
     pp_b_exact_modal_composition_word (pp_b_box \<circ> X)"
| diamond:
    "pp_b_exact_modal_composition_word X \<Longrightarrow>
     pp_b_exact_modal_composition_word (pp_b_diamond \<circ> X)"

lemma pp_b_exact_modal_composition_word_stock:
  assumes "pp_b_exact_modal_composition_word X"
  shows "X \<in> pp_b_exact_stock"
  using assms
proof induction
  case identity
  show ?case
    by (rule pp_b_exact_base_operators(1))
next
  case (complement X)
  show ?case
    using pp_b_exact_complement complement.IH
    by (rule pp_b_exact_stock_compose)
next
  case (box X)
  show ?case
    using pp_b_exact_base_operators(4) box.IH
    by (rule pp_b_exact_stock_compose)
next
  case (diamond X)
  show ?case
    using pp_b_exact_base_operators(5) diamond.IH
    by (rule pp_b_exact_stock_compose)
qed

theorem pp_b_exact_modal_composition_word_normal_form:
  assumes "pp_b_exact_modal_composition_word X"
  shows "X \<in> pp_b_exact_G \<or> pp_b_exact_modally_factorable X"
  using assms
proof induction
  case identity
  show ?case
    using pp_b_exact_G_id by blast
next
  case (complement X)
  show ?case
  proof (cases "X \<in> pp_b_exact_G")
    case True
    have "pp_b_complement \<circ> X \<in> pp_b_exact_G"
      using pp_b_exact_complement_reversible True
      by (rule pp_b_exact_G_compose)
    then show ?thesis by blast
  next
    case False
    then have factorable: "pp_b_exact_modally_factorable X"
      using complement.IH by blast
    obtain K H where K: "K \<in> pp_b_exact_G"
      and H: "H \<in> pp_b_exact_stock"
      and factor:
        "X = K \<circ> (pp_b_box \<circ> H) \<or>
         X = K \<circ> (pp_b_diamond \<circ> H)"
      using factorable
      unfolding pp_b_exact_modally_factorable_def by blast
    have prefix_G: "pp_b_complement \<circ> K \<in> pp_b_exact_G"
      using pp_b_exact_complement_reversible K
      by (rule pp_b_exact_G_compose)
    have
      "pp_b_complement \<circ> X =
        (pp_b_complement \<circ> K) \<circ> (pp_b_box \<circ> H) \<or>
       pp_b_complement \<circ> X =
        (pp_b_complement \<circ> K) \<circ> (pp_b_diamond \<circ> H)"
      using factor by (auto simp add: fun_eq_iff)
    then have
        "pp_b_exact_modally_factorable
          (pp_b_complement \<circ> X)"
      unfolding pp_b_exact_modally_factorable_def
      using prefix_G H by blast
    then show ?thesis by blast
  qed
next
  case (box X)
  have X_stock: "X \<in> pp_b_exact_stock"
    using box.hyps by (rule pp_b_exact_modal_composition_word_stock)
  have "pp_b_exact_modally_factorable (pp_b_box \<circ> X)"
  proof (unfold pp_b_exact_modally_factorable_def,
      rule bexI[of _ id], rule bexI[of _ X])
    show "pp_b_box \<circ> X =
        id \<circ> (pp_b_box \<circ> X) \<or>
        pp_b_box \<circ> X =
        id \<circ> (pp_b_diamond \<circ> X)"
      by simp
    show "X \<in> pp_b_exact_stock"
      by (rule X_stock)
    show "id \<in> pp_b_exact_G"
      by (rule pp_b_exact_G_id)
  qed
  then show ?case by blast
next
  case (diamond X)
  have X_stock: "X \<in> pp_b_exact_stock"
    using diamond.hyps
    by (rule pp_b_exact_modal_composition_word_stock)
  have "pp_b_exact_modally_factorable (pp_b_diamond \<circ> X)"
  proof (unfold pp_b_exact_modally_factorable_def,
      rule bexI[of _ id], rule bexI[of _ X])
    show "pp_b_diamond \<circ> X =
        id \<circ> (pp_b_box \<circ> X) \<or>
        pp_b_diamond \<circ> X =
        id \<circ> (pp_b_diamond \<circ> X)"
      by simp
    show "X \<in> pp_b_exact_stock"
      by (rule X_stock)
    show "id \<in> pp_b_exact_G"
      by (rule pp_b_exact_G_id)
  qed
  then show ?case by blast
qed

theorem pp_b_exact_modal_composition_word_right_cancellative_iff:
  assumes word: "pp_b_exact_modal_composition_word X"
  shows "pp_b_exact_right_cancellative X \<longleftrightarrow>
    X \<in> pp_b_exact_G"
proof
  assume cancellation: "pp_b_exact_right_cancellative X"
  have normal:
      "X \<in> pp_b_exact_G \<or> pp_b_exact_modally_factorable X"
    using word
    by (rule pp_b_exact_modal_composition_word_normal_form)
  show "X \<in> pp_b_exact_G"
  proof (rule disjE[OF normal])
    assume "X \<in> pp_b_exact_G"
    then show ?thesis .
  next
    assume "pp_b_exact_modally_factorable X"
    then have "\<not> pp_b_exact_right_cancellative X"
      by (rule pp_b_exact_modally_factorable_not_right_cancellative)
    then show ?thesis
      using cancellation by contradiction
  qed
next
  assume "X \<in> pp_b_exact_G"
  then show "pp_b_exact_right_cancellative X"
    by (rule pp_b_exact_reversible_right_cancellative)
qed

corollary pp_b_exact_modal_composition_word_no_negative_L2_witness:
  assumes word: "pp_b_exact_modal_composition_word X"
    and nonreversible: "X \<notin> pp_b_exact_G"
  shows "\<not> pp_b_exact_right_cancellative X"
  using word nonreversible
    pp_b_exact_modal_composition_word_right_cancellative_iff
  by blast

text \<open>
  Hence no composition word built from negation, necessity, and possibility
  can be the nonreversible right-cancellative operator required to refute L2.
  The unresolved negative search is now confined to closed logical operators
  that are not of this composition form, or, equivalently for present
  purposes, that do not become necessity- or possibility-headed after a
  reversible prefix is removed.  This is a classification of the displayed
  composition fragment, not a normalization theorem for all higher-order
  quantified terms in the complete definable stock.
\<close>

end
