theory Bacon_PP_ZF_Tree_Basis_Stock
  imports Bacon_PP_ZF_Tree_Generic_Seed
begin

section \<open>Stocks generated by countable cone-natural bases\<close>

definition pp_t_basis_stock ::
    "(otype \<Rightarrow> ZF set) \<Rightarrow>
      otype \<Rightarrow> bool list \<Rightarrow> ZF \<Rightarrow> bool"
where
  "pp_t_basis_stock D \<sigma> w x \<longleftrightarrow>
    Elem x (pp_t_domain \<sigma>) \<and>
    (\<exists>d \<in> D \<sigma>. pp_t_eqv \<sigma> w x d)"

definition pp_t_closed_logical_basis :: "otype \<Rightarrow> ZF set" where
  "pp_t_closed_logical_basis \<sigma> =
    {d. \<exists>M.
      [] \<turnstile> M : \<sigma> \<and>
      pp_logical_vocabulary M \<and>
      d = pp_t_closed_den M}"

lemma pp_t_closed_logical_basis_countable:
  "countable (pp_t_closed_logical_basis \<sigma>)"
proof -
  let ?Terms =
    "{M. [] \<turnstile> M : \<sigma> \<and>
      pp_logical_vocabulary M}"
  have terms_countable: "countable ?Terms"
    by simp
  have representation:
      "pp_t_closed_logical_basis \<sigma> =
        pp_t_closed_den ` ?Terms"
    unfolding pp_t_closed_logical_basis_def by auto
  show ?thesis
    unfolding representation
    using terms_countable by (rule countable_image)
qed

locale pp_t_stock_basis =
  fixes D :: "otype \<Rightarrow> ZF set"
  assumes basis_typed:
      "\<And>\<sigma> d. d \<in> D \<sigma> \<Longrightarrow>
        Elem d (pp_t_domain \<sigma>)"
    and basis_countable:
      "\<And>\<sigma>. countable (D \<sigma>)"
    and basis_cone_natural:
      "\<And>\<sigma> d s. d \<in> D \<sigma> \<Longrightarrow>
        pp_t_cone_rel \<sigma> s d d"
    and logical_basis:
      "\<And>\<sigma> M. [] \<turnstile> M : \<sigma> \<Longrightarrow>
        pp_logical_vocabulary M \<Longrightarrow>
        pp_t_closed_den M \<in> D \<sigma>"
    and basis_application:
      "\<And>\<sigma> \<tau> f x.
        f \<in> D (\<sigma> \<rightarrow>\<^sub>o \<tau>) \<Longrightarrow>
        x \<in> D \<sigma> \<Longrightarrow>
        \<exists>d \<in> D \<tau>.
          pp_t_eqv \<tau> [] (f \<acute> x) d"
begin

lemma pp_t_basis_stockI:
  assumes x: "Elem x (pp_t_domain \<sigma>)"
    and d: "d \<in> D \<sigma>"
    and xd: "pp_t_eqv \<sigma> w x d"
  shows "pp_t_basis_stock D \<sigma> w x"
  unfolding pp_t_basis_stock_def
  using x d xd by blast

lemma pp_t_basis_member_in_stock:
  assumes d: "d \<in> D \<sigma>"
  shows "pp_t_basis_stock D \<sigma> w d"
proof -
  have typed: "Elem d (pp_t_domain \<sigma>)"
    using basis_typed[OF d] .
  have refl: "pp_t_eqv \<sigma> w d d"
    using pp_t_eqv_reflexive[OF typed] .
  show ?thesis
    using typed d refl by (rule pp_t_basis_stockI)
qed

lemma pp_t_basis_stock_typed:
  assumes "pp_t_basis_stock D \<sigma> w x"
  shows "Elem x (pp_t_domain \<sigma>)"
  using assms unfolding pp_t_basis_stock_def by blast

lemma pp_t_basis_stock_persistent:
  assumes stock: "pp_t_basis_stock D \<sigma> w x"
    and future: "prefix w v"
  shows "pp_t_basis_stock D \<sigma> v x"
proof -
  obtain d where x: "Elem x (pp_t_domain \<sigma>)"
    and d: "d \<in> D \<sigma>"
    and xd: "pp_t_eqv \<sigma> w x d"
    using stock unfolding pp_t_basis_stock_def by blast
  have xd_v: "pp_t_eqv \<sigma> v x d"
    using pp_t_eqv_persistent[OF xd future] .
  show ?thesis
    using x d xd_v by (rule pp_t_basis_stockI)
qed

lemma pp_t_basis_stock_all_worlds_iff_root:
  "(\<forall>w. pp_t_basis_stock D \<sigma> w x)
    \<longleftrightarrow>
    pp_t_basis_stock D \<sigma> [] x"
proof
  assume all: "\<forall>w. pp_t_basis_stock D \<sigma> w x"
  show "pp_t_basis_stock D \<sigma> [] x"
    using all by blast
next
  assume root: "pp_t_basis_stock D \<sigma> [] x"
  show "\<forall>w. pp_t_basis_stock D \<sigma> w x"
  proof
    fix w
    show "pp_t_basis_stock D \<sigma> w x"
      using pp_t_basis_stock_persistent[
        OF root, of w] by simp
  qed
qed

lemma pp_t_basis_stock_admissible:
  "pp_t_predicate_admissible \<sigma>
    (pp_t_basis_stock D \<sigma>)"
proof (unfold pp_t_predicate_admissible_def, intro allI impI)
  fix w x y v
  assume x: "Elem x (pp_t_domain \<sigma>)"
    and y: "Elem y (pp_t_domain \<sigma>)"
    and xy: "pp_t_eqv \<sigma> w x y"
    and future: "prefix w v"
  have xy_v: "pp_t_eqv \<sigma> v x y"
    using pp_t_eqv_persistent[OF xy future] .
  have yx_v: "pp_t_eqv \<sigma> v y x"
    using pp_t_eqv_symmetric[OF x y xy_v] .
  show "pp_t_basis_stock D \<sigma> v x =
      pp_t_basis_stock D \<sigma> v y"
  proof
    assume stock_x: "pp_t_basis_stock D \<sigma> v x"
    then obtain d where d: "d \<in> D \<sigma>"
      and xd: "pp_t_eqv \<sigma> v x d"
      unfolding pp_t_basis_stock_def by blast
    have d_typed: "Elem d (pp_t_domain \<sigma>)"
      using basis_typed[OF d] .
    have yd: "pp_t_eqv \<sigma> v y d"
      using pp_t_eqv_transitive[
        OF y x d_typed yx_v xd] .
    show "pp_t_basis_stock D \<sigma> v y"
      using y d yd by (rule pp_t_basis_stockI)
  next
    assume stock_y: "pp_t_basis_stock D \<sigma> v y"
    then obtain d where d: "d \<in> D \<sigma>"
      and yd: "pp_t_eqv \<sigma> v y d"
      unfolding pp_t_basis_stock_def by blast
    have d_typed: "Elem d (pp_t_domain \<sigma>)"
      using basis_typed[OF d] .
    have xd: "pp_t_eqv \<sigma> v x d"
      using pp_t_eqv_transitive[
        OF x y d_typed xy_v yd] .
    show "pp_t_basis_stock D \<sigma> v x"
      using x d xd by (rule pp_t_basis_stockI)
  qed
qed

lemma pp_t_basis_stock_contains_logical_den:
  assumes typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  shows "pp_t_basis_stock D \<sigma> w (pp_t_closed_den M)"
  using pp_t_basis_member_in_stock[
    OF logical_basis[OF typed logical]] .

theorem pp_t_basis_stock_application_closed:
  assumes f_stock:
      "pp_t_basis_stock D (\<sigma> \<rightarrow>\<^sub>o \<tau>) w f"
    and x_stock: "pp_t_basis_stock D \<sigma> w x"
  shows "pp_t_basis_stock D \<tau> w (f \<acute> x)"
proof -
  obtain g where f: "Elem f (pp_t_domain (\<sigma> \<rightarrow>\<^sub>o \<tau>))"
    and g: "g \<in> D (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    and fg: "pp_t_eqv (\<sigma> \<rightarrow>\<^sub>o \<tau>) w f g"
    using f_stock unfolding pp_t_basis_stock_def by blast
  obtain y where x: "Elem x (pp_t_domain \<sigma>)"
    and y: "y \<in> D \<sigma>"
    and xy: "pp_t_eqv \<sigma> w x y"
    using x_stock unfolding pp_t_basis_stock_def by blast
  have g_typed: "Elem g (pp_t_domain (\<sigma> \<rightarrow>\<^sub>o \<tau>))"
    using basis_typed[OF g] .
  have y_typed: "Elem y (pp_t_domain \<sigma>)"
    using basis_typed[OF y] .
  obtain d where d: "d \<in> D \<tau>"
    and gyd_root: "pp_t_eqv \<tau> [] (g \<acute> y) d"
    using basis_application[OF g y] by blast
  have d_typed: "Elem d (pp_t_domain \<tau>)"
    using basis_typed[OF d] .
  have gyd: "pp_t_eqv \<tau> w (g \<acute> y) d"
    using pp_t_eqv_persistent[OF gyd_root, of w] by simp
  have fx_gy: "pp_t_eqv \<tau> w (f \<acute> x) (g \<acute> y)"
    using pp_t_app_respects[OF fg x y_typed xy] .
  have fx_typed: "Elem (f \<acute> x) (pp_t_domain \<tau>)"
    using pp_t_app_closed[OF f x] .
  have gy_typed: "Elem (g \<acute> y) (pp_t_domain \<tau>)"
    using pp_t_app_closed[OF g_typed y_typed] .
  have fx_d: "pp_t_eqv \<tau> w (f \<acute> x) d"
    using pp_t_eqv_transitive[
      OF fx_typed gy_typed d_typed fx_gy gyd] .
  show ?thesis
    using fx_typed d fx_d by (rule pp_t_basis_stockI)
qed

lemma pp_t_basis_stock_cone_iff:
  assumes x: "Elem x (pp_t_domain \<sigma>)"
    and y: "Elem y (pp_t_domain \<sigma>)"
    and xy: "pp_t_cone_rel \<sigma> s x y"
  shows "pp_t_basis_stock D \<sigma> (s @ u) x
    \<longleftrightarrow> pp_t_basis_stock D \<sigma> u y"
proof
  assume stock:
      "pp_t_basis_stock D \<sigma> (s @ u) x"
  then obtain d where d: "d \<in> D \<sigma>"
    and xd:
      "pp_t_eqv \<sigma> (s @ u) x d"
    unfolding pp_t_basis_stock_def by blast
  have d_typed: "Elem d (pp_t_domain \<sigma>)"
    using basis_typed[OF d] .
  have d_cone: "pp_t_cone_rel \<sigma> s d d"
    using basis_cone_natural[OF d] .
  have yd: "pp_t_eqv \<sigma> u y d"
    using UnconditionalCone.pp_t_cone_rel_eqv_iff[
      OF x y d_typed d_typed xy d_cone, of u] xd
    by blast
  show "pp_t_basis_stock D \<sigma> u y"
    using y d yd by (rule pp_t_basis_stockI)
next
  assume stock:
      "pp_t_basis_stock D \<sigma> u y"
  then obtain d where d: "d \<in> D \<sigma>"
    and yd: "pp_t_eqv \<sigma> u y d"
    unfolding pp_t_basis_stock_def by blast
  have d_typed: "Elem d (pp_t_domain \<sigma>)"
    using basis_typed[OF d] .
  have d_cone: "pp_t_cone_rel \<sigma> s d d"
    using basis_cone_natural[OF d] .
  have xd: "pp_t_eqv \<sigma> (s @ u) x d"
    using UnconditionalCone.pp_t_cone_rel_eqv_iff[
      OF x y d_typed d_typed xy d_cone, of u] yd
    by blast
  show "pp_t_basis_stock D \<sigma> (s @ u) x"
    using x d xd by (rule pp_t_basis_stockI)
qed

lemma pp_t_basis_classifier_cone_related:
  "pp_t_cone_rel (\<sigma> \<rightarrow>\<^sub>o Prop) s
    (pp_t_classifier \<sigma> (pp_t_basis_stock D \<sigma>))
    (pp_t_classifier \<sigma> (pp_t_basis_stock D \<sigma>))"
  unfolding pp_t_cone_rel.simps
  by (metis pp_t_classifier_holds pp_t_basis_stock_cone_iff)

section \<open>A generic seed for the basis unary stock\<close>

definition pp_b_basis_operator_stock :: "pp_b_operator set" where
  "pp_b_basis_operator_stock =
    pp_b_operator_of ` D (Prop \<rightarrow>\<^sub>o Prop)"

lemma pp_b_basis_operator_stock_countable:
  "countable pp_b_basis_operator_stock"
  unfolding pp_b_basis_operator_stock_def
  using basis_countable[of "Prop \<rightarrow>\<^sub>o Prop"]
  by (rule countable_image)

lemma pp_b_basis_operator_stock_equivariant:
  assumes "F \<in> pp_b_basis_operator_stock"
  shows "pp_b_equivariant F"
proof -
  obtain X where X: "X \<in> D (Prop \<rightarrow>\<^sub>o Prop)"
    and F: "F = pp_b_operator_of X"
    using assms unfolding pp_b_basis_operator_stock_def by blast
  have cone:
      "\<And>s. pp_t_cone_rel (Prop \<rightarrow>\<^sub>o Prop) s X X"
    using basis_cone_natural[OF X] .
  show ?thesis
    unfolding F
    using pp_t_cone_rel_operator_implies_equivariant[OF cone] .
qed

lemma pp_t_generic_seed_for_basis_operators:
  "\<exists>r. Elem r (pp_t_domain Prop) \<and>
    (\<forall>X \<in> D (Prop \<rightarrow>\<^sub>o Prop).
      ((\<forall>w. pp_t_holds (X \<acute> r) w) \<longrightarrow>
       (\<forall>q. Elem q (pp_t_domain Prop) \<longrightarrow>
          pp_t_holds (X \<acute> q) [])))"
proof -
  obtain R where generic:
      "\<forall>F \<in> pp_b_basis_operator_stock.
        pp_b_root_unary_recombination F R"
    using pp_b_generic_witness_for_countable_stock[
      OF pp_b_basis_operator_stock_countable
        pp_b_basis_operator_stock_equivariant]
    by blast
  let ?r = "pp_zf_of_b R"
  show ?thesis
  proof (intro exI[of _ ?r] conjI ballI impI)
    show "Elem ?r (pp_t_domain Prop)"
      by (rule pp_zf_of_b_in_domain)
  next
    fix X
    assume X: "X \<in> D (Prop \<rightarrow>\<^sub>o Prop)"
      and necessary: "\<forall>w. pp_t_holds (X \<acute> ?r) w"
    have operator:
        "pp_b_operator_of X \<in> pp_b_basis_operator_stock"
      using X unfolding pp_b_basis_operator_stock_def by blast
    have recombines:
        "pp_b_root_unary_recombination
          (pp_b_operator_of X) R"
      using generic operator by blast
    show "\<forall>q. Elem q (pp_t_domain Prop) \<longrightarrow>
        pp_t_holds (X \<acute> q) []"
      using pp_b_recombination_transfers_to_zf[
        OF recombines necessary] .
  qed
qed

theorem pp_t_generic_seed_recombines_basis_stock_at_root:
  "\<exists>r. Elem r (pp_t_domain Prop) \<and>
    pp_t_unary_recombines_at
      (pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop))
      r []"
proof -
  obtain r where r: "Elem r (pp_t_domain Prop)"
    and basis_recombines:
      "\<forall>X \<in> D (Prop \<rightarrow>\<^sub>o Prop).
        ((\<forall>w. pp_t_holds (X \<acute> r) w) \<longrightarrow>
         (\<forall>q. Elem q (pp_t_domain Prop) \<longrightarrow>
            pp_t_holds (X \<acute> q) []))"
    using pp_t_generic_seed_for_basis_operators by blast
  show ?thesis
  proof (intro exI[of _ r] conjI)
    show "Elem r (pp_t_domain Prop)"
      using r .
    show "pp_t_unary_recombines_at
        (pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop))
        r []"
      unfolding pp_t_unary_recombines_at_def
    proof (intro allI impI)
      fix Y q
      assume Y: "Elem Y (pp_t_domain (Prop \<rightarrow>\<^sub>o Prop))"
        and Y_stock:
          "pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop) [] Y"
        and necessary:
          "\<forall>v. prefix [] v \<longrightarrow>
            pp_t_holds (Y \<acute> r) v"
        and q: "Elem q (pp_t_domain Prop)"
      obtain X where X: "X \<in> D (Prop \<rightarrow>\<^sub>o Prop)"
        and YX:
          "pp_t_eqv (Prop \<rightarrow>\<^sub>o Prop) [] Y X"
        using Y_stock unfolding pp_t_basis_stock_def by blast
      have X_typed:
          "Elem X (pp_t_domain (Prop \<rightarrow>\<^sub>o Prop))"
        using basis_typed[OF X] .
      have X_necessary: "\<forall>v. pp_t_holds (X \<acute> r) v"
      proof
        fix v
        have YX_v:
            "pp_t_eqv (Prop \<rightarrow>\<^sub>o Prop) v Y X"
          using pp_t_eqv_persistent[OF YX, of v] by simp
        have rr: "pp_t_eqv Prop v r r"
          using pp_t_eqv_reflexive[OF r] .
        have applications:
            "pp_t_eqv Prop v (Y \<acute> r) (X \<acute> r)"
          using pp_t_app_respects[OF YX_v r r rr] .
        have Y_true: "pp_t_holds (Y \<acute> r) v"
          using necessary by simp
        show "pp_t_holds (X \<acute> r) v"
          using pp_t_prop_eqv_at[OF applications, of v]
            Y_true by simp
      qed
      have X_universal:
          "\<forall>p. Elem p (pp_t_domain Prop) \<longrightarrow>
            pp_t_holds (X \<acute> p) []"
        using basis_recombines X X_necessary by blast
      have Xq: "pp_t_holds (X \<acute> q) []"
        using X_universal q by blast
      have qq: "pp_t_eqv Prop [] q q"
        using pp_t_eqv_reflexive[OF q] .
      have YXq:
          "pp_t_eqv Prop [] (Y \<acute> q) (X \<acute> q)"
        using pp_t_app_respects[OF YX q q qq] .
      show "pp_t_holds (Y \<acute> q) []"
        using pp_t_prop_eqv_at[OF YXq, of "[]"] Xq by simp
    qed
  qed
qed

theorem pp_t_basis_root_recombination_transports_to_cone:
  assumes r: "Elem r (pp_t_domain Prop)"
    and root:
      "pp_t_unary_recombines_at
        (pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop))
        r []"
  shows "pp_t_unary_recombines_at
    (pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop))
    (pp_t_cone_lift w r) w"
  unfolding pp_t_unary_recombines_at_def
proof (intro allI impI)
  fix Y q
  assume Y:
      "Elem Y (pp_t_domain (Prop \<rightarrow>\<^sub>o Prop))"
    and Y_stock:
      "pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop) w Y"
    and necessary:
      "\<forall>v. prefix w v \<longrightarrow>
        pp_t_holds (Y \<acute> pp_t_cone_lift w r) v"
    and q: "Elem q (pp_t_domain Prop)"
  let ?Z = "pp_t_cone_restrict (Prop \<rightarrow>\<^sub>o Prop) w Y"
  let ?p = "pp_t_cone_restrict Prop w q"
  have Z:
      "Elem ?Z (pp_t_domain (Prop \<rightarrow>\<^sub>o Prop))"
    using pp_t_cone_restrict_in_domain[OF Y] .
  have p: "Elem ?p (pp_t_domain Prop)"
    using pp_t_cone_restrict_in_domain[OF q] .
  have YZ:
      "pp_t_cone_rel (Prop \<rightarrow>\<^sub>o Prop) w Y ?Z"
    using pp_t_cone_restrict_related[OF Y] .
  have lift_r:
      "pp_t_cone_rel Prop w (pp_t_cone_lift w r) r"
    using pp_t_cone_extend_related[OF r, of w]
    by simp
  have qp: "pp_t_cone_rel Prop w q ?p"
    using pp_t_cone_restrict_related[OF q] .
  have Z_stock:
      "pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop) [] ?Z"
    using pp_t_basis_stock_cone_iff[
      OF Y Z YZ, of "[]"] Y_stock
    by simp
  have Z_necessary: "\<forall>u. pp_t_holds (?Z \<acute> r) u"
  proof
    fix u
    have output_rel:
        "pp_t_cone_rel Prop w
          (Y \<acute> pp_t_cone_lift w r) (?Z \<acute> r)"
      using YZ pp_t_cone_lift_in_domain r lift_r by auto
    have left_true:
        "pp_t_holds (Y \<acute> pp_t_cone_lift w r) (w @ u)"
      using necessary by simp
    show "pp_t_holds (?Z \<acute> r) u"
      using output_rel left_true by auto
  qed
  have Z_universal:
      "\<forall>a. Elem a (pp_t_domain Prop) \<longrightarrow>
        pp_t_holds (?Z \<acute> a) []"
    using root Z Z_stock Z_necessary
    unfolding pp_t_unary_recombines_at_def by blast
  have Zp_true: "pp_t_holds (?Z \<acute> ?p) []"
    using Z_universal p by blast
  have output_rel:
      "pp_t_cone_rel Prop w (Y \<acute> q) (?Z \<acute> ?p)"
    using YZ q p qp by auto
  have output_all:
      "\<forall>u. pp_t_holds (Y \<acute> q) (w @ u)
        \<longleftrightarrow> pp_t_holds (?Z \<acute> ?p) u"
    using output_rel by simp
  have at_root:
      "pp_t_holds (Y \<acute> q) (w @ [])
        \<longleftrightarrow> pp_t_holds (?Z \<acute> ?p) []"
    using output_all[rule_format, of "[]"] .
  show "pp_t_holds (Y \<acute> q) w"
    using at_root Zp_true by simp
qed

corollary pp_t_basis_generic_seed_at_every_world:
  "\<exists>r. Elem r (pp_t_domain Prop) \<and>
    (\<forall>w. pp_t_unary_recombines_at
      (pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop))
      (pp_t_cone_lift w r) w)"
proof -
  obtain r where r: "Elem r (pp_t_domain Prop)"
    and root:
      "pp_t_unary_recombines_at
        (pp_t_basis_stock D (Prop \<rightarrow>\<^sub>o Prop))
        r []"
    using pp_t_generic_seed_recombines_basis_stock_at_root
    by blast
  show ?thesis
    using r pp_t_basis_root_recombination_transports_to_cone[
      OF r root] by blast
qed

end

interpretation ClosedLogicalBasis:
  pp_t_stock_basis pp_t_closed_logical_basis
proof
  fix \<sigma> d
  assume "d \<in> pp_t_closed_logical_basis \<sigma>"
  then obtain M where typed: "[] \<turnstile> M : \<sigma>"
    and d: "d = pp_t_closed_den M"
    unfolding pp_t_closed_logical_basis_def by blast
  show "Elem d (pp_t_domain \<sigma>)"
    unfolding d
    using pp_t_closed_den_in_domain[OF typed] .
next
  fix \<sigma>
  show "countable (pp_t_closed_logical_basis \<sigma>)"
    by (rule pp_t_closed_logical_basis_countable)
next
  fix \<sigma> d s
  assume "d \<in> pp_t_closed_logical_basis \<sigma>"
  then obtain M where typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
    and d: "d = pp_t_closed_den M"
    unfolding pp_t_closed_logical_basis_def by blast
  show "pp_t_cone_rel \<sigma> s d d"
    unfolding d
    using UnconditionalCone.pp_t_closed_logical_den_cone_related[
      OF typed logical] .
next
  fix \<sigma> M
  assume typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  show "pp_t_closed_den M \<in> pp_t_closed_logical_basis \<sigma>"
    unfolding pp_t_closed_logical_basis_def
    using typed logical by blast
next
  fix \<sigma> \<tau> f x
  assume f:
      "f \<in> pp_t_closed_logical_basis
        (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    and x: "x \<in> pp_t_closed_logical_basis \<sigma>"
  obtain M where M_typed:
      "[] \<turnstile> M : (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    and M_logical: "pp_logical_vocabulary M"
    and f: "f = pp_t_closed_den M"
    using f unfolding pp_t_closed_logical_basis_def by blast
  obtain N where N_typed: "[] \<turnstile> N : \<sigma>"
    and N_logical: "pp_logical_vocabulary N"
    and x: "x = pp_t_closed_den N"
    using x unfolding pp_t_closed_logical_basis_def by blast
  have app_typed: "[] \<turnstile> App M N : \<tau>"
    using M_typed N_typed by (rule has_type.App)
  have app_logical: "pp_logical_vocabulary (App M N)"
    using M_logical N_logical
    by (simp add: pp_logical_vocabulary_def)
  let ?d = "pp_t_closed_den (App M N)"
  have d: "?d \<in> pp_t_closed_logical_basis \<tau>"
    unfolding pp_t_closed_logical_basis_def
    using app_typed app_logical by blast
  have app_eq: "f \<acute> x = ?d"
    unfolding f x
    by (simp add: pp_t_closed_den_def)
  have d_typed: "Elem ?d (pp_t_domain \<tau>)"
    using pp_t_closed_den_in_domain[OF app_typed] .
  have refl: "pp_t_eqv \<tau> [] ?d ?d"
    using pp_t_eqv_reflexive[OF d_typed] .
  show "\<exists>d \<in> pp_t_closed_logical_basis \<tau>.
      pp_t_eqv \<tau> [] (f \<acute> x) d"
  proof (rule bexI[of _ ?d])
    show "pp_t_eqv \<tau> [] (f \<acute> x) ?d"
      using refl app_eq by simp
    show "?d \<in> pp_t_closed_logical_basis \<tau>"
      using d .
  qed
qed

lemma pp_t_basis_stock_closed_logical_basis:
  "pp_t_basis_stock pp_t_closed_logical_basis \<sigma> w x
    \<longleftrightarrow>
    pp_t_closed_logical_stock \<sigma> w x"
  unfolding pp_t_basis_stock_def
    pp_t_closed_logical_basis_def
    pp_t_closed_logical_stock_def
  by blast

end
