theory Bacon_PP_ZF_Tree_Logical_Stock
  imports Bacon_PP_ZF_Tree_Frame
begin

section \<open>The least admissible stock generated by closed logical terms\<close>

definition pp_t_closed_env :: "nat \<Rightarrow> ZF" where
  "pp_t_closed_env n = Empty"

definition pp_t_closed_den :: "oterm \<Rightarrow> ZF" where
  "pp_t_closed_den M =
    pp_t_eval pp_t_default_constants pp_t_closed_env M"

lemma pp_t_eval_const_free:
  assumes "consts_of M = {}"
  shows "pp_t_eval C \<rho> M = pp_t_eval D \<rho> M"
  using assms
proof (induction M arbitrary: \<rho>)
  case (Var n)
  then show ?case by simp
next
  case (Const c \<sigma>)
  then show ?case by simp
next
  case (App M N)
  then show ?case by simp
next
  case (Lam \<sigma> M)
  then show ?case by simp
next
  case (Eq \<sigma> M N)
  then show ?case by simp
next
  case (Neg M)
  then show ?case by simp
next
  case (Conj M N)
  then show ?case by simp
next
  case (Disj M N)
  then show ?case by simp
next
  case (Imp M N)
  then show ?case by simp
next
  case (Forall \<sigma> M)
  then show ?case by simp
next
  case (Exists \<sigma> M)
  then show ?case by simp
qed

lemma pp_t_empty_env_typed:
  "pp_t_env_typed [] \<rho>"
  by (simp add: pp_t_env_typed_def lookup_def)

lemma pp_t_empty_env_eqv:
  "pp_t_env_eqv w [] \<rho> \<eta>"
  by (simp add: pp_t_env_eqv_def pp_t_env_typed_def lookup_def)

lemma pp_t_closed_den_in_domain:
  assumes typed: "[] \<turnstile> M : \<sigma>"
  shows "Elem (pp_t_closed_den M) (pp_t_domain \<sigma>)"
  unfolding pp_t_closed_den_def
  using DefaultTreeConstants.pp_t_eval_type[
    OF typed pp_t_empty_env_typed]
  by (simp add: pp_t_dom_def)

definition pp_t_closed_logical_stock ::
    "otype \<Rightarrow> bool list \<Rightarrow> ZF \<Rightarrow> bool"
  where
  "pp_t_closed_logical_stock \<sigma> w x \<longleftrightarrow>
    Elem x (pp_t_domain \<sigma>) \<and>
    (\<exists>M.
      [] \<turnstile> M : \<sigma> \<and>
      pp_logical_vocabulary M \<and>
      pp_t_eqv \<sigma> w x (pp_t_closed_den M))"

lemma pp_t_closed_logical_stockI:
  assumes typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  shows "pp_t_closed_logical_stock \<sigma> w (pp_t_closed_den M)"
proof -
  have domain: "Elem (pp_t_closed_den M) (pp_t_domain \<sigma>)"
    using pp_t_closed_den_in_domain[OF typed] .
  have refl:
      "pp_t_eqv \<sigma> w (pp_t_closed_den M) (pp_t_closed_den M)"
    using pp_t_eqv_reflexive[OF domain] .
  show ?thesis
    unfolding pp_t_closed_logical_stock_def
    using domain typed logical refl by blast
qed

lemma pp_t_closed_logical_stock_persistent:
  assumes stock: "pp_t_closed_logical_stock \<sigma> w x"
    and future: "prefix w v"
  shows "pp_t_closed_logical_stock \<sigma> v x"
proof -
  obtain M where x: "Elem x (pp_t_domain \<sigma>)"
    and typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
    and xM: "pp_t_eqv \<sigma> w x (pp_t_closed_den M)"
    using stock unfolding pp_t_closed_logical_stock_def by blast
  have xM_v:
      "pp_t_eqv \<sigma> v x (pp_t_closed_den M)"
    using pp_t_eqv_persistent[OF xM future] .
  show ?thesis
    unfolding pp_t_closed_logical_stock_def
    using x typed logical xM_v by blast
qed

lemma pp_t_closed_logical_stock_all_worlds_iff_root:
  "(\<forall>w. pp_t_closed_logical_stock \<sigma> w x)
    \<longleftrightarrow>
    pp_t_closed_logical_stock \<sigma> [] x"
proof
  assume all: "\<forall>w. pp_t_closed_logical_stock \<sigma> w x"
  show "pp_t_closed_logical_stock \<sigma> [] x"
    using all by blast
next
  assume root: "pp_t_closed_logical_stock \<sigma> [] x"
  show "\<forall>w. pp_t_closed_logical_stock \<sigma> w x"
  proof
    fix w
    show "pp_t_closed_logical_stock \<sigma> w x"
      using pp_t_closed_logical_stock_persistent[
        OF root, of w] by simp
  qed
qed

lemma pp_t_closed_logical_stock_admissible:
  "pp_t_predicate_admissible \<sigma>
    (pp_t_closed_logical_stock \<sigma>)"
proof (unfold pp_t_predicate_admissible_def, intro allI impI)
  fix w x y v
  assume x: "Elem x (pp_t_domain \<sigma>)"
    and y: "Elem y (pp_t_domain \<sigma>)"
    and xy: "pp_t_eqv \<sigma> w x y"
    and future: "prefix w v"
  have xy_v: "pp_t_eqv \<sigma> v x y"
    using pp_t_eqv_persistent[OF xy future] .
  have yx_v: "pp_t_eqv \<sigma> v y x"
    using pp_t_eqv_symmetric[OF x y xy_v] .
  show "pp_t_closed_logical_stock \<sigma> v x =
      pp_t_closed_logical_stock \<sigma> v y"
  proof
    assume stock_x: "pp_t_closed_logical_stock \<sigma> v x"
    then obtain M where typed: "[] \<turnstile> M : \<sigma>"
      and logical: "pp_logical_vocabulary M"
      and xM: "pp_t_eqv \<sigma> v x (pp_t_closed_den M)"
      unfolding pp_t_closed_logical_stock_def by blast
    have den: "Elem (pp_t_closed_den M) (pp_t_domain \<sigma>)"
      using pp_t_closed_den_in_domain[OF typed] .
    have yM: "pp_t_eqv \<sigma> v y (pp_t_closed_den M)"
      using pp_t_eqv_transitive[OF y x den yx_v xM] .
    show "pp_t_closed_logical_stock \<sigma> v y"
      unfolding pp_t_closed_logical_stock_def
      using y typed logical yM by blast
  next
    assume stock_y: "pp_t_closed_logical_stock \<sigma> v y"
    then obtain M where typed: "[] \<turnstile> M : \<sigma>"
      and logical: "pp_logical_vocabulary M"
      and yM: "pp_t_eqv \<sigma> v y (pp_t_closed_den M)"
      unfolding pp_t_closed_logical_stock_def by blast
    have den: "Elem (pp_t_closed_den M) (pp_t_domain \<sigma>)"
      using pp_t_closed_den_in_domain[OF typed] .
    have xM: "pp_t_eqv \<sigma> v x (pp_t_closed_den M)"
      using pp_t_eqv_transitive[OF x y den xy_v yM] .
    show "pp_t_closed_logical_stock \<sigma> v x"
      unfolding pp_t_closed_logical_stock_def
      using x typed logical xM by blast
  qed
qed

theorem pp_t_closed_logical_stock_application_closed:
  assumes f_stock:
      "pp_t_closed_logical_stock (\<sigma> \<rightarrow>\<^sub>o \<tau>) w f"
    and x_stock: "pp_t_closed_logical_stock \<sigma> w x"
  shows "pp_t_closed_logical_stock \<tau> w (f \<acute> x)"
proof -
  obtain M where M_type: "[] \<turnstile> M : (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    and M_logical: "pp_logical_vocabulary M"
    and fM:
      "pp_t_eqv (\<sigma> \<rightarrow>\<^sub>o \<tau>) w f
        (pp_t_closed_den M)"
    using f_stock unfolding pp_t_closed_logical_stock_def by blast
  obtain N where N_type: "[] \<turnstile> N : \<sigma>"
    and N_logical: "pp_logical_vocabulary N"
    and xN: "pp_t_eqv \<sigma> w x (pp_t_closed_den N)"
    using x_stock unfolding pp_t_closed_logical_stock_def by blast
  have f_domain: "Elem f (pp_t_domain (\<sigma> \<rightarrow>\<^sub>o \<tau>))"
    using f_stock unfolding pp_t_closed_logical_stock_def by blast
  have x_domain: "Elem x (pp_t_domain \<sigma>)"
    using x_stock unfolding pp_t_closed_logical_stock_def by blast
  have M_domain:
      "Elem (pp_t_closed_den M)
        (pp_t_domain (\<sigma> \<rightarrow>\<^sub>o \<tau>))"
    using pp_t_closed_den_in_domain[OF M_type] .
  have N_domain: "Elem (pp_t_closed_den N) (pp_t_domain \<sigma>)"
    using pp_t_closed_den_in_domain[OF N_type] .
  have app_related:
      "pp_t_eqv \<tau> w (f \<acute> x)
        ((pp_t_closed_den M) \<acute> (pp_t_closed_den N))"
    using pp_t_app_respects[OF fM x_domain N_domain xN] .
  have app_type: "[] \<turnstile> App M N : \<tau>"
    using M_type N_type by (rule has_type.App)
  have app_logical: "pp_logical_vocabulary (App M N)"
    using M_logical N_logical
    by (simp add: pp_logical_vocabulary_def)
  have app_den:
      "pp_t_closed_den (App M N) =
        (pp_t_closed_den M) \<acute> (pp_t_closed_den N)"
    by (simp add: pp_t_closed_den_def)
  have app_domain: "Elem (f \<acute> x) (pp_t_domain \<tau>)"
    using pp_t_app_closed[OF f_domain x_domain] .
  show ?thesis
    unfolding pp_t_closed_logical_stock_def
  proof (intro conjI)
    show "Elem (f \<acute> x) (pp_t_domain \<tau>)"
      using app_domain .
    show "\<exists>A.
        [] \<turnstile> A : \<tau> \<and>
        pp_logical_vocabulary A \<and>
        pp_t_eqv \<tau> w (f \<acute> x) (pp_t_closed_den A)"
    proof (rule exI[of _ "App M N"], intro conjI)
      show "[] \<turnstile> App M N : \<tau>"
        using app_type .
      show "pp_logical_vocabulary (App M N)"
        using app_logical .
      show "pp_t_eqv \<tau> w (f \<acute> x) (pp_t_closed_den (App M N))"
        using app_related app_den by simp
    qed
  qed
qed

theorem pp_t_closed_logical_stock_least:
  assumes admissible:
      "\<And>\<sigma>. pp_t_predicate_admissible \<sigma> (Pure \<sigma>)"
    and contains:
      "\<And>\<sigma> M w. [] \<turnstile> M : \<sigma> \<Longrightarrow>
        pp_logical_vocabulary M \<Longrightarrow>
        Pure \<sigma> w (pp_t_closed_den M)"
    and stock: "pp_t_closed_logical_stock \<sigma> w x"
  shows "Pure \<sigma> w x"
proof -
  obtain M where x: "Elem x (pp_t_domain \<sigma>)"
    and typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
    and xM: "pp_t_eqv \<sigma> w x (pp_t_closed_den M)"
    using stock unfolding pp_t_closed_logical_stock_def by blast
  have den: "Elem (pp_t_closed_den M) (pp_t_domain \<sigma>)"
    using pp_t_closed_den_in_domain[OF typed] .
  have equivalence:
      "Pure \<sigma> w x \<longleftrightarrow>
        Pure \<sigma> w (pp_t_closed_den M)"
    using admissible[of \<sigma>] x den xM
    unfolding pp_t_predicate_admissible_def
    by blast
  show ?thesis
    using equivalence contains[OF typed logical] by blast
qed

lemma pp_t_closed_logical_stock_contains_eval:
  assumes typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  shows "pp_t_closed_logical_stock \<sigma> w (pp_t_eval C \<rho> M)"
proof -
  have const_free: "consts_of M = {}"
    using logical unfolding pp_logical_vocabulary_def .
  have change_constants:
      "pp_t_eval C \<rho> M =
        pp_t_eval pp_t_default_constants \<rho> M"
    using pp_t_eval_const_free[OF const_free] .
  have related:
      "pp_t_eqv \<sigma> w
        (pp_t_eval pp_t_default_constants \<rho> M)
        (pp_t_eval pp_t_default_constants pp_t_closed_env M)"
    using DefaultTreeConstants.pp_t_eval_respects[
      OF typed pp_t_empty_env_eqv] .
  have domain:
      "Elem (pp_t_eval C \<rho> M) (pp_t_domain \<sigma>)"
    unfolding change_constants
    using DefaultTreeConstants.pp_t_eval_type[
      OF typed pp_t_empty_env_typed]
    by (simp add: pp_t_dom_def)
  show ?thesis
    unfolding pp_t_closed_logical_stock_def pp_t_closed_den_def
  proof (intro conjI)
    show "Elem (pp_t_eval C \<rho> M) (pp_t_domain \<sigma>)"
      using domain .
    show "\<exists>N.
        [] \<turnstile> N : \<sigma> \<and>
        pp_logical_vocabulary N \<and>
        pp_t_eqv \<sigma> w (pp_t_eval C \<rho> M)
          (pp_t_eval pp_t_default_constants pp_t_closed_env N)"
    proof (rule exI[of _ M], intro conjI)
      show "[] \<turnstile> M : \<sigma>"
        using typed .
      show "pp_logical_vocabulary M"
        using logical .
      show "pp_t_eqv \<sigma> w (pp_t_eval C \<rho> M)
          (pp_t_eval pp_t_default_constants pp_t_closed_env M)"
        using related change_constants by simp
    qed
  qed
qed

interpretation ClosedLogicalTree:
  pp_t_moving_internal_parameters pp_t_closed_logical_stock
  by standard (rule pp_t_closed_logical_stock_admissible)

theorem pp_t_closed_logical_purity_gvalid:
  assumes typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  shows "ClosedLogicalTree.MovingTreeConstants.TreeHenkin.gvalid \<Gamma>
    (pp_pure \<sigma> M)"
proof (rule
    ClosedLogicalTree.MovingTreeConstants.TreeHenkin.gvalidI)
  fix env w
  assume "env_ok (map pp_t_dom \<Gamma>) env"
  have eval_pure:
      "pp_t_holds
        (pp_t_eval
          (pp_t_moving_internal_constants pp_t_closed_logical_stock)
          (pp_t_list_env env) (pp_pure \<sigma> M)) w
      \<longleftrightarrow>
        pp_t_closed_logical_stock \<sigma> w
          (pp_t_eval
            (pp_t_moving_internal_constants pp_t_closed_logical_stock)
            (pp_t_list_env env) M)"
    using ClosedLogicalTree.pp_t_moving_eval_pure_holds[
      OF typed pp_t_empty_env_typed, where w=w] .
  have stock:
      "pp_t_closed_logical_stock \<sigma> w
        (pp_t_eval
          (pp_t_moving_internal_constants pp_t_closed_logical_stock)
          (pp_t_list_env env) M)"
    using pp_t_closed_logical_stock_contains_eval[
      OF typed logical] .
  show "pp_t_holds
      (ClosedLogicalTree.MovingTreeConstants.pp_t_den
        (pp_pure \<sigma> M) env) w"
    unfolding ClosedLogicalTree.MovingTreeConstants.pp_t_den_def
    using eval_pure stock by blast
qed

lemma pp_t_closed_logical_application_closure_holds_iff:
  "pp_t_holds
      (pp_t_eval
        (pp_t_moving_internal_constants pp_t_closed_logical_stock)
        \<rho> (pp_application_closure \<sigma> \<tau>)) w
    \<longleftrightarrow>
    (\<forall>f. Elem f (pp_t_domain (\<sigma> \<rightarrow>\<^sub>o \<tau>)) \<longrightarrow>
      (\<forall>x. Elem x (pp_t_domain \<sigma>) \<longrightarrow>
        pp_t_closed_logical_stock (\<sigma> \<rightarrow>\<^sub>o \<tau>) w f \<and>
        pp_t_closed_logical_stock \<sigma> w x \<longrightarrow>
        pp_t_closed_logical_stock \<tau> w (f \<acute> x)))"
  by (simp add: pp_application_closure_def pp_pure_def
      pp_t_classifier_holds pp_t_app_closed extend_env.simps)

theorem pp_t_closed_logical_application_closure_gvalid:
  "ClosedLogicalTree.MovingTreeConstants.TreeHenkin.gvalid \<Gamma>
    (pp_application_closure \<sigma> \<tau>)"
proof (rule
    ClosedLogicalTree.MovingTreeConstants.TreeHenkin.gvalidI)
  fix env w
  assume "env_ok (map pp_t_dom \<Gamma>) env"
  show "pp_t_holds
      (ClosedLogicalTree.MovingTreeConstants.pp_t_den
        (pp_application_closure \<sigma> \<tau>) env) w"
    unfolding ClosedLogicalTree.MovingTreeConstants.pp_t_den_def
      pp_t_closed_logical_application_closure_holds_iff
    using pp_t_closed_logical_stock_application_closed by blast
qed

section \<open>A closed logical settling operator\<close>

definition pp_t_settles_operator :: oterm where
  "pp_t_settles_operator =
    Lam Prop
      (Disj
        (\<diamond>\<^sub>o (\<box>\<^sub>o (Var 0)))
        (\<diamond>\<^sub>o (\<box>\<^sub>o (Neg (Var 0)))))"

lemma pp_t_settles_operator_typed:
  "[] \<turnstile> pp_t_settles_operator : (Prop \<rightarrow>\<^sub>o Prop)"
  unfolding pp_t_settles_operator_def
  by (intro has_type.Lam has_type.Disj typed_ObjDiamond
      typed_ObjBox has_type.Neg has_type.Var)
    simp_all

lemma pp_t_settles_operator_logical:
  "pp_logical_vocabulary pp_t_settles_operator"
  by (simp add: pp_logical_vocabulary_def pp_t_settles_operator_def
      ObjDiamond_def ObjBox_def ObjTrue_def)

lemma pp_t_settles_den_in_domain:
  "Elem (pp_t_closed_den pp_t_settles_operator)
    (pp_t_domain (Prop \<rightarrow>\<^sub>o Prop))"
  using pp_t_closed_den_in_domain[OF pp_t_settles_operator_typed] .

lemma pp_t_settles_den_in_stock:
  "pp_t_closed_logical_stock (Prop \<rightarrow>\<^sub>o Prop) w
    (pp_t_closed_den pp_t_settles_operator)"
  using pp_t_closed_logical_stockI[
    OF pp_t_settles_operator_typed pp_t_settles_operator_logical] .

lemma pp_t_box_neg_holds_iff_false:
  "pp_t_holds
      (pp_t_eval C \<rho> (\<box>\<^sub>o (Neg A))) w
    \<longleftrightarrow>
      pp_t_eqv Prop w
        (pp_t_eval C \<rho> A) (pp_zf_truth False)"
  unfolding pp_t_eval_ObjBox_holds
  by simp

lemma pp_t_settles_den_holds:
  assumes q: "Elem q (pp_t_domain Prop)"
  shows "pp_t_holds
      ((pp_t_closed_den pp_t_settles_operator) \<acute> q) w
    \<longleftrightarrow>
      ((\<exists>v. prefix w v \<and>
          pp_t_eqv Prop v q (pp_zf_truth True)) \<or>
       (\<exists>v. prefix w v \<and>
          pp_t_eqv Prop v q (pp_zf_truth False)))"
proof -
  have beta:
      "(pp_t_closed_den pp_t_settles_operator) \<acute> q =
        pp_t_eval pp_t_default_constants
          (extend_env q pp_t_closed_env)
          (Disj
            (\<diamond>\<^sub>o (\<box>\<^sub>o (Var 0)))
            (\<diamond>\<^sub>o (\<box>\<^sub>o (Neg (Var 0)))))"
    using q
    by (simp add: pp_t_closed_den_def pp_t_settles_operator_def
        Lambda_app)
  show ?thesis
    unfolding beta
    using pp_t_eval_ObjDiamond_holds[
        of pp_t_default_constants
          "extend_env q pp_t_closed_env" "\<box>\<^sub>o (Var 0)" w]
      pp_t_eval_ObjDiamond_holds[
        of pp_t_default_constants
          "extend_env q pp_t_closed_env"
          "\<box>\<^sub>o (Neg (Var 0))" w]
      pp_t_eval_ObjBox_holds[
        of pp_t_default_constants
          "extend_env q pp_t_closed_env" "Var 0"]
      pp_t_box_neg_holds_iff_false[
        of pp_t_default_constants
          "extend_env q pp_t_closed_env" "Var 0"]
    by simp
qed

section \<open>The nonsettling proposition and the Recombination failure\<close>

definition pp_t_parity_prop :: ZF where
  "pp_t_parity_prop =
    pp_t_prop (\<lambda>w. even (length w))"

lemma pp_t_parity_prop_in_domain:
  "Elem pp_t_parity_prop (pp_t_domain Prop)"
  unfolding pp_t_parity_prop_def
  by (rule pp_t_prop_in_domain)

lemma pp_t_parity_prop_holds[simp]:
  "pp_t_holds pp_t_parity_prop w \<longleftrightarrow> even (length w)"
  by (simp add: pp_t_parity_prop_def)

lemma pp_t_parity_prop_not_true:
  "\<not> pp_t_eqv Prop w pp_t_parity_prop (pp_zf_truth True)"
proof
  assume eqv:
      "pp_t_eqv Prop w pp_t_parity_prop (pp_zf_truth True)"
  have at_w:
      "pp_t_holds pp_t_parity_prop w \<longleftrightarrow>
        pp_t_holds (pp_zf_truth True) w"
    using pp_t_prop_eqv_at[OF eqv, of w] by simp
  have at_child:
      "pp_t_holds pp_t_parity_prop (w @ [True]) \<longleftrightarrow>
        pp_t_holds (pp_zf_truth True) (w @ [True])"
    using pp_t_prop_eqv_at[OF eqv, of "w @ [True]"] by simp
  show False
    using at_w at_child by simp
qed

lemma pp_t_parity_prop_not_false:
  "\<not> pp_t_eqv Prop w pp_t_parity_prop (pp_zf_truth False)"
proof
  assume eqv:
      "pp_t_eqv Prop w pp_t_parity_prop (pp_zf_truth False)"
  have at_w:
      "pp_t_holds pp_t_parity_prop w \<longleftrightarrow>
        pp_t_holds (pp_zf_truth False) w"
    using pp_t_prop_eqv_at[OF eqv, of w] by simp
  have at_child:
      "pp_t_holds pp_t_parity_prop (w @ [True]) \<longleftrightarrow>
        pp_t_holds (pp_zf_truth False) (w @ [True])"
    using pp_t_prop_eqv_at[OF eqv, of "w @ [True]"] by simp
  show False
    using at_w at_child by simp
qed

lemma pp_t_moving_seed_false_on_right:
  "pp_t_eqv Prop (w @ [False])
    (pp_t_moving_seed w) (pp_zf_truth False)"
proof (simp only: pp_t_eqv.simps, intro allI impI)
  fix v
  assume false_v: "prefix (w @ [False]) v"
  have not_true_v: "\<not> prefix (w @ [True]) v"
    using pp_tree_split_no_common_successor[of w] false_v
    unfolding pp_tree_access_def by blast
  show "pp_t_holds (pp_t_moving_seed w) v =
      pp_t_holds (pp_zf_truth False) v"
    using not_true_v by simp
qed

lemma pp_t_moving_seed_eventually_settles:
  assumes future: "prefix w u"
  shows "\<exists>v. prefix u v \<and>
      (pp_t_eqv Prop v
        (pp_t_moving_seed w) (pp_zf_truth True) \<or>
       pp_t_eqv Prop v
        (pp_t_moving_seed w) (pp_zf_truth False))"
proof -
  let ?v = "u @ [True]"
  have uv: "prefix u ?v"
    by simp
  have wv: "prefix w ?v"
    using future uv by (rule prefix_order.trans)
  have w_ne_v: "w \<noteq> ?v"
  proof
    assume "w = ?v"
    then have "length w = length u + 1"
      by simp
    moreover have "length w \<le> length u"
      using prefix_length_le[OF future] .
    ultimately show False by simp
  qed
  have strict: "strict_prefix w ?v"
    using wv w_ne_v by (rule strict_prefixI)
  then obtain b zs where split: "?v = w @ b # zs"
    by (rule strict_prefixE')
  have branch: "prefix (w @ [b]) ?v"
    using split by (simp add: prefix_def)
  show ?thesis
  proof (cases b)
    case False
    have false_branch: "prefix (w @ [False]) ?v"
      using branch False by simp
    have base:
        "pp_t_eqv Prop (w @ [False])
          (pp_t_moving_seed w) (pp_zf_truth False)"
      by (rule pp_t_moving_seed_false_on_right)
    have settled:
        "pp_t_eqv Prop ?v
          (pp_t_moving_seed w) (pp_zf_truth False)"
      using pp_t_eqv_persistent[OF base false_branch] .
    show ?thesis
      using uv settled by blast
  next
    case True
    have true_branch: "prefix (w @ [True]) ?v"
      using branch True by simp
    have base:
        "pp_t_eqv Prop (w @ [True])
          (pp_t_moving_seed w) (pp_zf_truth True)"
      by (rule pp_t_moving_seed_true_on_left)
    have settled:
        "pp_t_eqv Prop ?v
          (pp_t_moving_seed w) (pp_zf_truth True)"
      using pp_t_eqv_persistent[OF base true_branch] .
    show ?thesis
      using uv settled by blast
  qed
qed

lemma pp_t_settles_necessary_of_moving_seed:
  "\<forall>u. prefix w u \<longrightarrow>
    pp_t_holds
      ((pp_t_closed_den pp_t_settles_operator) \<acute>
        pp_t_moving_seed w) u"
proof (intro allI impI)
  fix u
  assume future: "prefix w u"
  obtain v where uv: "prefix u v"
    and settled:
      "pp_t_eqv Prop v
          (pp_t_moving_seed w) (pp_zf_truth True) \<or>
       pp_t_eqv Prop v
          (pp_t_moving_seed w) (pp_zf_truth False)"
    using pp_t_moving_seed_eventually_settles[OF future] by blast
  show "pp_t_holds
      ((pp_t_closed_den pp_t_settles_operator) \<acute>
        pp_t_moving_seed w) u"
    using pp_t_settles_den_holds[
      OF pp_t_moving_seed_in_domain, where w=u] uv settled by blast
qed

lemma pp_t_settles_fails_on_parity:
  "\<not> pp_t_holds
    ((pp_t_closed_den pp_t_settles_operator) \<acute>
      pp_t_parity_prop) w"
  using pp_t_settles_den_holds[
      OF pp_t_parity_prop_in_domain, of w]
    pp_t_parity_prop_not_true pp_t_parity_prop_not_false
  by blast

theorem pp_t_closed_logical_stock_not_recombines:
  "\<not> pp_t_unary_recombines_at
    (pp_t_closed_logical_stock (Prop \<rightarrow>\<^sub>o Prop))
    (pp_t_moving_seed w) w"
proof
  assume recombines:
      "pp_t_unary_recombines_at
        (pp_t_closed_logical_stock (Prop \<rightarrow>\<^sub>o Prop))
        (pp_t_moving_seed w) w"
  have universal:
      "\<forall>q. Elem q (pp_t_domain Prop) \<longrightarrow>
        pp_t_holds
          ((pp_t_closed_den pp_t_settles_operator) \<acute> q) w"
    using recombines pp_t_settles_den_in_domain
      pp_t_settles_den_in_stock
      pp_t_settles_necessary_of_moving_seed
    unfolding pp_t_unary_recombines_at_def by blast
  have "pp_t_holds
      ((pp_t_closed_den pp_t_settles_operator) \<acute>
        pp_t_parity_prop) w"
    using universal pp_t_parity_prop_in_domain by blast
  then show False
    using pp_t_settles_fails_on_parity by blast
qed

theorem pp_t_any_logical_stock_not_recombines:
  assumes contains_settles:
      "Pure w (pp_t_closed_den pp_t_settles_operator)"
  shows "\<not> pp_t_unary_recombines_at Pure
    (pp_t_moving_seed w) w"
proof
  assume recombines:
      "pp_t_unary_recombines_at Pure (pp_t_moving_seed w) w"
  have universal:
      "\<forall>q. Elem q (pp_t_domain Prop) \<longrightarrow>
        pp_t_holds
          ((pp_t_closed_den pp_t_settles_operator) \<acute> q) w"
    using recombines pp_t_settles_den_in_domain contains_settles
      pp_t_settles_necessary_of_moving_seed
    unfolding pp_t_unary_recombines_at_def by blast
  have "pp_t_holds
      ((pp_t_closed_den pp_t_settles_operator) \<acute>
        pp_t_parity_prop) w"
    using universal pp_t_parity_prop_in_domain by blast
  then show False
    using pp_t_settles_fails_on_parity by blast
qed

corollary pp_t_logical_purity_blocks_moving_recombination:
  assumes logical_purity:
      "\<And>\<sigma> M w. [] \<turnstile> M : \<sigma> \<Longrightarrow>
        pp_logical_vocabulary M \<Longrightarrow>
        Pure \<sigma> w (pp_t_closed_den M)"
  shows "\<not> pp_t_unary_recombines_at
    (Pure (Prop \<rightarrow>\<^sub>o Prop)) (pp_t_moving_seed w) w"
  by (rule pp_t_any_logical_stock_not_recombines)
    (rule logical_purity[
      OF pp_t_settles_operator_typed pp_t_settles_operator_logical])

lemma pp_t_three_extensions_index_two[simp]:
  "extend_env q (extend_env r (extend_env X \<rho>)) 2 = X"
  by (simp add: numeral_2_eq_2)

lemma pp_t_closed_logical_unary_recombination_holds_iff:
  "pp_t_holds
      (pp_t_eval
        (pp_t_moving_internal_constants pp_t_closed_logical_stock)
        \<rho> pp_unary_recombination) w
    \<longleftrightarrow>
    (\<forall>X. Elem X (pp_t_domain (Prop \<rightarrow>\<^sub>o Prop)) \<longrightarrow>
      (\<forall>r. Elem r (pp_t_domain Prop) \<longrightarrow>
        (pp_t_closed_logical_stock (Prop \<rightarrow>\<^sub>o Prop) w X \<and>
         pp_t_moving_fundamental_at Prop w r) \<longrightarrow>
        ((\<forall>v. prefix w v \<longrightarrow> pp_t_holds (X \<acute> r) v) \<longrightarrow>
         (\<forall>q. Elem q (pp_t_domain Prop) \<longrightarrow>
            pp_t_holds (X \<acute> q) w))))"
  by (simp add: pp_unary_recombination_def pp_pure_def pp_fun_def
      pp_t_classifier_holds pp_t_prop_eqv_truth_iff
      pp_t_eval_ObjBox_holds extend_env.simps)

theorem pp_t_closed_logical_unary_recombination_fails:
  "\<not> pp_t_holds
    (pp_t_eval
      (pp_t_moving_internal_constants pp_t_closed_logical_stock)
      \<rho> pp_unary_recombination) w"
proof
  assume holds:
      "pp_t_holds
        (pp_t_eval
          (pp_t_moving_internal_constants pp_t_closed_logical_stock)
          \<rho> pp_unary_recombination) w"
  have semantic:
      "\<forall>X. Elem X (pp_t_domain (Prop \<rightarrow>\<^sub>o Prop)) \<longrightarrow>
        (\<forall>r. Elem r (pp_t_domain Prop) \<longrightarrow>
          (pp_t_closed_logical_stock (Prop \<rightarrow>\<^sub>o Prop) w X \<and>
           pp_t_moving_fundamental_at Prop w r) \<longrightarrow>
          ((\<forall>v. prefix w v \<longrightarrow> pp_t_holds (X \<acute> r) v) \<longrightarrow>
           (\<forall>q. Elem q (pp_t_domain Prop) \<longrightarrow>
              pp_t_holds (X \<acute> q) w)))"
    using holds
      unfolding pp_t_closed_logical_unary_recombination_holds_iff .
  have seed_fundamental:
      "pp_t_moving_fundamental_at Prop w (pp_t_moving_seed w)"
    using pp_t_eqv_reflexive[OF pp_t_moving_seed_in_domain] by simp
  have universal:
      "\<forall>q. Elem q (pp_t_domain Prop) \<longrightarrow>
        pp_t_holds
          ((pp_t_closed_den pp_t_settles_operator) \<acute> q) w"
    using semantic pp_t_settles_den_in_domain
      pp_t_moving_seed_in_domain pp_t_settles_den_in_stock
      seed_fundamental pp_t_settles_necessary_of_moving_seed
    by blast
  have "pp_t_holds
      ((pp_t_closed_den pp_t_settles_operator) \<acute>
        pp_t_parity_prop) w"
    using universal pp_t_parity_prop_in_domain by blast
  then show False
    using pp_t_settles_fails_on_parity by blast
qed

theorem pp_t_closed_logical_unary_recombination_not_gvalid:
  "\<not> ClosedLogicalTree.MovingTreeConstants.TreeHenkin.gvalid []
    pp_unary_recombination"
proof
  assume valid:
      "ClosedLogicalTree.MovingTreeConstants.TreeHenkin.gvalid []
        pp_unary_recombination"
  have holds:
      "pp_t_holds
        (ClosedLogicalTree.MovingTreeConstants.pp_t_den
          pp_unary_recombination []) []"
    using valid
    by (rule
      ClosedLogicalTree.MovingTreeConstants.TreeHenkin.gvalidD)
      simp
  have not_holds:
      "\<not> pp_t_holds
        (ClosedLogicalTree.MovingTreeConstants.pp_t_den
          pp_unary_recombination []) []"
    unfolding ClosedLogicalTree.MovingTreeConstants.pp_t_den_def
    by (rule pp_t_closed_logical_unary_recombination_fails)
  show False
    using holds not_holds by blast
qed

end
