from __future__ import annotations

from pathlib import Path

from finite_core_search.axioms import Profile

from .candidates import Candidate


def emit_purity_audit(
    output_dir: Path,
    profile: Profile,
    candidates: list[Candidate],
    session_name: str = "Goodman_Pure_Diagonal_Audit",
) -> tuple[Path, Path]:
    """Emit one Isabelle audit proving every listed diagonal pure."""
    output_dir.mkdir(parents=True, exist_ok=True)
    theory_path = output_dir / "Pure_Diagonal_Audit.thy"
    root_path = output_dir / "ROOT"

    lemmas: list[str] = []
    theorem_names: list[str] = []
    for index, candidate in enumerate(candidates):
        theorem_name = f"pure_diagonal_{index}"
        theorem_names.append(theorem_name)
        builder = candidate.builder.isabelle()
        lemmas.extend(
            [
                f"lemma {theorem_name}:",
                f'  "[] ; finite_core_profile_axioms {profile.isabelle}',
                "    \\<turnstile>\\<^sub>CEV\\<^sup>+",
                "      pp_pure (Prop \\<rightarrow>\\<^sub>o Prop)",
                f"        (App ({builder}) "
                "(pp_Pure (Prop \\<rightarrow>\\<^sub>o Prop)))\"",
                "proof (rule finite_core_pure_logical_builder_application)",
                f'  show "infer_type [] ({builder}) =',
                "      Some ((((Prop \\<rightarrow>\\<^sub>o Prop) "
                "\\<rightarrow>\\<^sub>o Prop)",
                "        \\<rightarrow>\\<^sub>o "
                "(Prop \\<rightarrow>\\<^sub>o Prop)))\"",
                "    by (simp add: lookup_def)",
                f'  show "consts_of ({builder}) = {{}}" by simp',
                "qed",
                "",
            ]
        )

    target_list = ", ".join(f"@{{thm {name}}}" for name in theorem_names)
    theory_path.write_text(
        "\n".join(
            [
                "theory Pure_Diagonal_Audit",
                "  imports "
                "Goodman_CEVplus_Canonical.Bacon_PP_Fresh_Finite_Core_Search",
                "begin",
                "",
                "text \\<open>",
                "  Generated by pure_diagonal_search. Each theorem below is",
                "  checked from the exact constant-free builder syntax. The",
                "  external enumerator is not a proof authority.",
                "\\<close>",
                "",
                *lemmas,
                "ML \\<open>",
                f"val targets = [{target_list}]",
                "val oracles = maps (fn th => Thm_Deps.all_oracles [th]) targets",
                "val hyps = maps Thm.hyps_of targets",
                "val tpairs = maps Thm.tpairs_of targets",
                "val _ =",
                "  if null oracles andalso null hyps andalso null tpairs",
                "  then writeln (\"PURE-DIAGONAL-AUDIT-CLEAN: \" ^",
                "    Int.toString (length targets) ^ \" candidates\")",
                "  else error \"PURE-DIAGONAL-AUDIT-NOT-CLEAN\"",
                "\\<close>",
                "",
                "end",
                "",
            ]
        )
    )
    root_path.write_text(
        "\n".join(
            [
                f"session {session_name} = Goodman_CEVplus_Canonical +",
                "  options [timeout = 900]",
                "  theories",
                "    Pure_Diagonal_Audit",
                "",
            ]
        )
    )
    return theory_path, root_path
