theory Bacon_PP_Attainment_Failure
  imports Bacon_PP_Attainment
begin

section \<open>A definable body at \<open>Prop\<close> that defeats attainment\<close>

text \<open>
  \<open>Bacon_PP_Attainment\<close> leaves exactly one gap: bodies at quantified type \<open>Prop\<close>
  that are neither monotone nor antitone.  This theory fills it with an explicit
  example, and the example is as innocent as it could be.

  The body is non-contingency,

  \begin{center}
  \<open>f X = \<box>X \<or> \<box>\<not>X\<close>,
  \end{center}

  which is Pure-free, uses no parameter, and has modal depth one.  It is mixed in
  variance exactly as the earlier analysis predicted: it fails to be monotone because
  \<open>{}\<close> is decided everywhere while its supersets need not be, and fails to be
  antitone because \<open>UNIV\<close> is decided everywhere while its subsets need not be.

  The domain is generated by the propositions \<open>C\<^sub>n = {w. length w \<le> n}\<close>.  A world
  \<open>i\<close> decides \<open>C\<^sub>n\<close> exactly when \<open>n < length i\<close>: deep enough into the tree the cone
  contains only long words and \<open>C\<^sub>n\<close> is uniformly false there, while at shallower
  worlds the cone contains both short and long words.  So the sets of worlds deciding
  the generators shrink to nothing, but every \emph{finite} family of generators is
  decided somewhere.

  Consequently the intersection over the whole domain is empty while every finite
  subfamily leaves worlds over, and no finite part of the domain attains the limit.
  The closure lemmas below show that generating a Boolean and modal algebra from the
  \<open>C\<^sub>n\<close> does not repair this, since decidedness is inherited by complements,
  intersections and boxes.

  One caveat is recorded at the end and should not be glossed: this settles the
  question for Boolean- and box-closed domains, which is the form in which the
  question was posed.  It does not yet show that the \<open>C\<^sub>n\<close> arise as denotations in a
  domain generated from a seed.
\<close>

subsection \<open>Local complement and intersection\<close>

lemma pp_view_Compl_local:
  "pp_view i (- X) = - pp_view i X"
  by (auto simp: pp_view_def)

lemma pp_view_Int_local:
  "pp_view i (X \<inter> Y) = pp_view i X \<inter> pp_view i Y"
  by (auto simp: pp_view_def)

lemma pp_sem_box_empty[simp]:
  "pp_sem_box {} = {}"
  by (auto simp: pp_sem_box_def pp_view_def)

lemma pp_sem_box_UNIV[simp]:
  "pp_sem_box UNIV = UNIV"
  by (auto simp: pp_sem_box_def pp_view_def)

subsection \<open>Non-contingency as a body\<close>

definition pp_decided :: "pp_sem_prop \<Rightarrow> pp_sem_prop" where
  "pp_decided X = pp_sem_box X \<union> pp_sem_box (- X)"

lemma pp_decided_iff:
  "i \<in> pp_decided X \<longleftrightarrow>
    pp_view i X = UNIV \<or> pp_view i X = {}"
proof -
  have "i \<in> pp_sem_box (- X) \<longleftrightarrow> pp_view i X = {}"
    by (auto simp: pp_sem_box_def pp_view_Compl_local)
  moreover have "i \<in> pp_sem_box X \<longleftrightarrow> pp_view i X = UNIV"
    by (simp add: pp_sem_box_def)
  ultimately show ?thesis
    by (auto simp: pp_decided_def)
qed

subsection \<open>Decidedness survives the Boolean and modal closure\<close>

lemma pp_decided_Compl[simp]:
  "pp_decided (- X) = pp_decided X"
proof (rule set_eqI)
  fix i
  have compl_UNIV: "(- pp_view i X = UNIV) = (pp_view i X = {})"
    by auto
  have compl_empty: "(- pp_view i X = {}) = (pp_view i X = UNIV)"
    by auto
  have "i \<in> pp_decided (- X) \<longleftrightarrow>
      (- pp_view i X = UNIV \<or> - pp_view i X = {})"
    by (simp add: pp_decided_iff pp_view_Compl_local)
  also have "... \<longleftrightarrow>
      (pp_view i X = UNIV \<or> pp_view i X = {})"
    using compl_UNIV compl_empty by blast
  also have "... \<longleftrightarrow> i \<in> pp_decided X"
    by (simp add: pp_decided_iff)
  finally show "i \<in> pp_decided (- X) \<longleftrightarrow> i \<in> pp_decided X" .
qed

lemma pp_decided_Int:
  assumes "i \<in> pp_decided X" and "i \<in> pp_decided Y"
  shows "i \<in> pp_decided (X \<inter> Y)"
  using assms by (auto simp: pp_decided_iff pp_view_Int_local)

lemma pp_decided_box:
  assumes "i \<in> pp_decided X"
  shows "i \<in> pp_decided (pp_sem_box X)"
proof -
  have "pp_view i (pp_sem_box X) = pp_sem_box (pp_view i X)"
    by (rule pp_sem_box_equivariant)
  then show ?thesis
    using assms by (auto simp: pp_decided_iff)
qed

text \<open>
  So a world deciding every member of a finite family decides everything the family
  generates.  Closing the domain under the connectives and the modality therefore
  cannot shrink the set of deciding worlds below what the generators already give.
\<close>

subsection \<open>The body is neither monotone nor antitone\<close>

definition pp_shortprop :: "nat \<Rightarrow> pp_sem_prop" where
  "pp_shortprop n = {w. length w \<le> n}"

lemma pp_view_shortprop:
  "pp_view i (pp_shortprop n) =
    {j. length j + length i \<le> n}"
  by (auto simp: pp_view_def pp_shortprop_def)

theorem pp_decided_shortprop:
  "i \<in> pp_decided (pp_shortprop n) \<longleftrightarrow> n < length i"
proof (cases "n < length i")
  case True
  have "pp_view i (pp_shortprop n) = {}"
    using True by (auto simp: pp_view_shortprop)
  then show ?thesis
    using True by (simp add: pp_decided_iff)
next
  case False
  then have le: "length i \<le> n" by simp
  have root: "[] \<in> pp_view i (pp_shortprop n)"
    using le by (simp add: pp_view_shortprop)
  have long: "pp_zeros (Suc n) \<notin> pp_view i (pp_shortprop n)"
    by (simp add: pp_view_shortprop)
  have "pp_view i (pp_shortprop n) \<noteq> UNIV"
    using long by blast
  moreover have "pp_view i (pp_shortprop n) \<noteq> {}"
    using root by blast
  ultimately show ?thesis
    using False by (simp add: pp_decided_iff)
qed

lemma pp_decided_empty[simp]: "pp_decided {} = UNIV"
  by (auto simp: pp_decided_iff pp_view_def)

lemma pp_decided_UNIV[simp]: "pp_decided UNIV = UNIV"
  by (auto simp: pp_decided_iff pp_view_def)

theorem pp_decided_not_monotone:
  "\<not> (\<forall>X Y. X \<subseteq> Y \<longrightarrow> pp_decided X \<subseteq> pp_decided Y)"
proof
  assume mono: "\<forall>X Y. X \<subseteq> Y \<longrightarrow> pp_decided X \<subseteq> pp_decided Y"
  have "{} \<subseteq> pp_shortprop 0" by simp
  then have "pp_decided {} \<subseteq> pp_decided (pp_shortprop 0)"
    using mono by blast
  then have "([] :: pp_word) \<in> pp_decided (pp_shortprop 0)"
    by auto
  then show False
    by (simp add: pp_decided_shortprop)
qed

theorem pp_decided_not_antitone:
  "\<not> (\<forall>X Y. X \<subseteq> Y \<longrightarrow> pp_decided Y \<subseteq> pp_decided X)"
proof
  assume anti: "\<forall>X Y. X \<subseteq> Y \<longrightarrow> pp_decided Y \<subseteq> pp_decided X"
  have "pp_shortprop 0 \<subseteq> UNIV" by simp
  then have "pp_decided UNIV \<subseteq> pp_decided (pp_shortprop 0)"
    using anti by blast
  then have "([] :: pp_word) \<in> pp_decided (pp_shortprop 0)"
    by auto
  then show False
    by (simp add: pp_decided_shortprop)
qed

subsection \<open>Attainment fails\<close>

lemma pp_forall_over_shortprops_empty:
  "pp_forall_over (range pp_shortprop) pp_decided = {}"
proof (rule set_eqI)
  fix i :: pp_word
  have mem: "pp_shortprop (length i) \<in> range pp_shortprop"
    by blast
  have "i \<notin> pp_decided (pp_shortprop (length i))"
    by (simp add: pp_decided_shortprop)
  then have "\<not> (\<forall>X \<in> range pp_shortprop. i \<in> pp_decided X)"
    using mem by blast
  then show "i \<in> pp_forall_over (range pp_shortprop) pp_decided \<longleftrightarrow>
      i \<in> {}"
    by (simp add: pp_forall_over_iff)
qed

lemma pp_forall_over_finite_shortprops_nonempty:
  assumes S_sub: "S \<subseteq> range pp_shortprop"
    and S_fin: "finite S"
  shows "pp_forall_over S pp_decided \<noteq> {}"
proof -
  have choose_index: "\<exists>n. X = pp_shortprop n" if "X \<in> S" for X
    using that S_sub by blast
  obtain nn where nn: "\<And>X. X \<in> S \<Longrightarrow> X = pp_shortprop (nn X)"
    using choose_index by metis
  let ?N = "Max (insert 0 (nn ` S))"
  have finite_set: "finite (insert 0 (nn ` S))"
    using S_fin by simp
  have bound: "nn X \<le> ?N" if "X \<in> S" for X
    using finite_set that by (simp add: Max_ge)
  let ?i = "pp_zeros (Suc ?N)"
  have "?i \<in> pp_forall_over S pp_decided"
    unfolding pp_forall_over_iff
  proof (intro ballI)
    fix X
    assume X: "X \<in> S"
    have "nn X < length ?i"
      using bound[OF X] by simp
    then have "?i \<in> pp_decided (pp_shortprop (nn X))"
      by (simp add: pp_decided_shortprop)
    then show "?i \<in> pp_decided X"
      using nn[OF X] by simp
  qed
  then show ?thesis by blast
qed

theorem pp_decided_defeats_attainment:
  "\<not> pp_finitely_attained (range pp_shortprop) pp_decided"
proof
  assume "pp_finitely_attained (range pp_shortprop) pp_decided"
  then obtain S where S_sub: "S \<subseteq> range pp_shortprop"
    and S_fin: "finite S"
    and cuts: "pp_forall_over S pp_decided \<subseteq>
      pp_forall_over (range pp_shortprop) pp_decided"
    unfolding pp_finitely_attained_def by blast
  have "pp_forall_over S pp_decided \<subseteq> {}"
    using cuts pp_forall_over_shortprops_empty by simp
  moreover have "pp_forall_over S pp_decided \<noteq> {}"
    using S_sub S_fin
    by (rule pp_forall_over_finite_shortprops_nonempty)
  ultimately show False by simp
qed

text \<open>
  And since attainment fails, so does persistence: along the increasing chain of
  finite initial segments of the generators, the stage values never reach the limit.
\<close>

definition pp_shortstage :: "nat \<Rightarrow> pp_sem_prop set" where
  "pp_shortstage n = pp_shortprop ` {k. k < n}"

lemma pp_shortstage_increasing:
  "pp_shortstage n \<subseteq> pp_shortstage (Suc n)"
  by (auto simp: pp_shortstage_def)

lemma pp_shortstage_Union:
  "(\<Union>n. pp_shortstage n) = range pp_shortprop"
  by (auto simp: pp_shortstage_def)

theorem pp_decided_denotation_does_not_persist:
  "\<forall>n. pp_forall_over (pp_shortstage n) pp_decided \<noteq>
       pp_forall_over (\<Union>m. pp_shortstage m) pp_decided"
proof (intro allI)
  fix n
  have sub: "pp_shortstage n \<subseteq> range pp_shortprop"
    by (auto simp: pp_shortstage_def)
  have fin: "finite (pp_shortstage n)"
    by (simp add: pp_shortstage_def)
  have "pp_forall_over (pp_shortstage n) pp_decided \<noteq> {}"
    using sub fin by (rule pp_forall_over_finite_shortprops_nonempty)
  moreover have
      "pp_forall_over (\<Union>m. pp_shortstage m) pp_decided = {}"
    using pp_forall_over_shortprops_empty pp_shortstage_Union by simp
  ultimately show "pp_forall_over (pp_shortstage n) pp_decided \<noteq>
      pp_forall_over (\<Union>m. pp_shortstage m) pp_decided"
    by simp
qed

subsection \<open>What this settles, and the caveat\<close>

text \<open>
  Settled.  The gap left by \<open>Bacon_PP_Attainment\<close> is real, and it is not exotic.  A
  Pure-free, parameter-free body of modal depth one --- non-contingency --- defeats
  attainment, and hence persistence, over a domain of propositions.  The closure
  lemmas show that the failure is not an artefact of taking too small a domain:
  decidedness passes to complements, intersections and boxes, so generating a Boolean
  and modal algebra from the \<open>C\<^sub>n\<close> leaves the deciding worlds exactly where they
  were.  So the positive results of the previous theory really do stop at the monotone
  and antitone cases.

  The caveat.  What has been exhibited is a legitimate domain of propositions closed
  under the connectives and the modality, not a domain shown to arise as the Henkin
  closure of a language over a seed.  To promote this into an obstruction for the
  consistency construction one would still have to realize the \<open>C\<^sub>n\<close>, or something
  with the same decidedness behaviour, as denotations of terms over a seed.  Since
  \<open>C\<^sub>n\<close> is definable from the depth predicate and the seed is contingent by
  \<open>pp_seed_not_extreme\<close>, that looks plausible, but it is not proved here and should
  not be assumed.
\<close>

end
