theory Bacon_PP_ZF_Tree_Boolean_Probe_Closure
  imports
    Higher_Order_Metaphysics_PP_ZF_Secondary.Bacon_PP_ZF_Tree_Complemented_Symmetrized_Singleton
begin

section \<open>The Boolean closure generated by the first probe\<close>

abbreviation pp_t_boolean_probe_unary_type :: otype where
  "pp_t_boolean_probe_unary_type \<equiv> Prop \<rightarrow>\<^sub>o Prop"

abbreviation pp_t_boolean_probe_transformer_type :: otype where
  "pp_t_boolean_probe_transformer_type \<equiv>
    pp_t_boolean_probe_unary_type
      \<rightarrow>\<^sub>o pp_t_boolean_probe_unary_type"

abbreviation pp_t_boolean_probe_builder_type :: otype where
  "pp_t_boolean_probe_builder_type \<equiv>
    pp_t_boolean_probe_unary_type
      \<rightarrow>\<^sub>o pp_t_boolean_probe_transformer_type"

definition pp_t_unary_output_conjunction :: oterm where
  "pp_t_unary_output_conjunction =
    Lam pp_t_boolean_probe_unary_type
      (Lam pp_t_boolean_probe_unary_type
        (Lam Prop
          (Conj
            (App (Var 2) (Var 0))
            (App (Var 1) (Var 0)))))"

lemma pp_t_unary_output_conjunction_typed:
  "[] \<turnstile> pp_t_unary_output_conjunction :
    pp_t_boolean_probe_builder_type"
  by (rule infer_type_sound)
    (simp add: pp_t_unary_output_conjunction_def lookup_def)

lemma pp_t_unary_output_conjunction_logical:
  "pp_logical_vocabulary pp_t_unary_output_conjunction"
  by (simp add: pp_t_unary_output_conjunction_def
      pp_logical_vocabulary_def)

abbreviation pp_t_unary_output_conjunction_den :: ZF where
  "pp_t_unary_output_conjunction_den \<equiv>
    pp_t_closed_den pp_t_unary_output_conjunction"

lemma pp_t_unary_output_conjunction_den_in_domain:
  "Elem pp_t_unary_output_conjunction_den
    (pp_t_domain pp_t_boolean_probe_builder_type)"
  by (rule pp_t_closed_den_in_domain)
    (rule pp_t_unary_output_conjunction_typed)

datatype pp_t_probe_boolean_expr =
    PPProbeBooleanLogical oterm
  | PPProbeBooleanGenerator
  | PPProbeBooleanNeg pp_t_probe_boolean_expr
  | PPProbeBooleanConj
      pp_t_probe_boolean_expr pp_t_probe_boolean_expr

instantiation pp_t_probe_boolean_expr :: countable
begin

instance
  by countable_datatype

end

fun pp_t_probe_boolean_expr_valid ::
    "pp_t_probe_boolean_expr \<Rightarrow> bool"
where
  "pp_t_probe_boolean_expr_valid
      (PPProbeBooleanLogical M) =
    ([] \<turnstile> M : pp_t_boolean_probe_unary_type
      \<and> pp_logical_vocabulary M)"
| "pp_t_probe_boolean_expr_valid PPProbeBooleanGenerator = True"
| "pp_t_probe_boolean_expr_valid (PPProbeBooleanNeg E) =
    pp_t_probe_boolean_expr_valid E"
| "pp_t_probe_boolean_expr_valid (PPProbeBooleanConj E F) =
    (pp_t_probe_boolean_expr_valid E
      \<and> pp_t_probe_boolean_expr_valid F)"

fun pp_t_probe_boolean_expr_den ::
    "pp_t_probe_boolean_expr \<Rightarrow> ZF"
where
  "pp_t_probe_boolean_expr_den (PPProbeBooleanLogical M) =
    pp_t_closed_den M"
| "pp_t_probe_boolean_expr_den PPProbeBooleanGenerator =
    pp_t_symmetrized_closed_stock_probe"
| "pp_t_probe_boolean_expr_den (PPProbeBooleanNeg E) =
    pp_t_closed_den pp_t_unary_output_negator
      \<acute> pp_t_probe_boolean_expr_den E"
| "pp_t_probe_boolean_expr_den (PPProbeBooleanConj E F) =
    (pp_t_unary_output_conjunction_den
      \<acute> pp_t_probe_boolean_expr_den E)
      \<acute> pp_t_probe_boolean_expr_den F"

lemma pp_t_probe_boolean_expr_den_in_domain:
  assumes valid: "pp_t_probe_boolean_expr_valid E"
  shows "Elem (pp_t_probe_boolean_expr_den E)
    (pp_t_domain pp_t_boolean_probe_unary_type)"
  using valid
proof (induction E)
  case (PPProbeBooleanLogical M)
  have typed:
      "[] \<turnstile> M : pp_t_boolean_probe_unary_type"
    using PPProbeBooleanLogical.prems by simp
  show ?case
    using pp_t_closed_den_in_domain[OF typed]
    by simp
next
  case PPProbeBooleanGenerator
  show ?case
    using pp_t_symmetrized_closed_stock_probe_in_domain
    by simp
next
  case (PPProbeBooleanNeg E)
  have negator:
      "Elem (pp_t_closed_den pp_t_unary_output_negator)
        (pp_t_domain pp_t_boolean_probe_transformer_type)"
    by (rule pp_t_closed_den_in_domain)
      (rule pp_t_unary_output_negator_typed)
  have E_domain:
      "Elem (pp_t_probe_boolean_expr_den E)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
    using PPProbeBooleanNeg by simp
  show ?case
    using pp_t_app_closed[OF negator E_domain]
    by simp
next
  case (PPProbeBooleanConj E F)
  have E_domain:
      "Elem (pp_t_probe_boolean_expr_den E)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
    using PPProbeBooleanConj by simp
  have F_domain:
      "Elem (pp_t_probe_boolean_expr_den F)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
    using PPProbeBooleanConj by simp
  have first:
      "Elem
        (pp_t_unary_output_conjunction_den
          \<acute> pp_t_probe_boolean_expr_den E)
        (pp_t_domain pp_t_boolean_probe_transformer_type)"
    by (rule pp_t_app_closed[
      OF pp_t_unary_output_conjunction_den_in_domain E_domain])
  show ?case
    using pp_t_app_closed[OF first F_domain]
    by simp
qed

lemma pp_t_probe_boolean_expr_den_cone_natural:
  assumes valid: "pp_t_probe_boolean_expr_valid E"
  shows "pp_t_cone_rel pp_t_boolean_probe_unary_type s
    (pp_t_probe_boolean_expr_den E)
    (pp_t_probe_boolean_expr_den E)"
  using valid
proof (induction E)
  case (PPProbeBooleanLogical M)
  have typed:
      "[] \<turnstile> M : pp_t_boolean_probe_unary_type"
    and logical: "pp_logical_vocabulary M"
    using PPProbeBooleanLogical.prems by simp_all
  have cone:
      "pp_t_cone_rel pp_t_boolean_probe_unary_type s
        (pp_t_closed_den M) (pp_t_closed_den M)"
    by (rule
      UnconditionalCone.pp_t_closed_logical_den_cone_related[
        OF typed logical])
  show ?case
    using cone by simp
next
  case PPProbeBooleanGenerator
  have cone:
      "pp_t_cone_rel pp_t_boolean_probe_unary_type s
        pp_t_symmetrized_closed_stock_probe
        pp_t_symmetrized_closed_stock_probe"
    using pp_t_complemented_symmetrized_probe_cone_natural
    unfolding pp_t_complemented_closed_stock_probe_eq .
  show ?case
    using cone by simp
next
  case (PPProbeBooleanNeg E)
  have negator:
      "pp_t_cone_rel pp_t_boolean_probe_transformer_type s
        (pp_t_closed_den pp_t_unary_output_negator)
        (pp_t_closed_den pp_t_unary_output_negator)"
    by (rule
      UnconditionalCone.pp_t_closed_logical_den_cone_related[
        OF pp_t_unary_output_negator_typed
          pp_t_unary_output_negator_logical])
  have E_domain:
      "Elem (pp_t_probe_boolean_expr_den E)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
  proof -
    have E_valid: "pp_t_probe_boolean_expr_valid E"
      using PPProbeBooleanNeg.prems by simp
    show ?thesis
      by (rule pp_t_probe_boolean_expr_den_in_domain[OF E_valid])
  qed
  show ?case
    using negator E_domain PPProbeBooleanNeg
    by simp
next
  case (PPProbeBooleanConj E F)
  have conjunction:
      "pp_t_cone_rel pp_t_boolean_probe_builder_type s
        pp_t_unary_output_conjunction_den
        pp_t_unary_output_conjunction_den"
    by (rule
      UnconditionalCone.pp_t_closed_logical_den_cone_related[
        OF pp_t_unary_output_conjunction_typed
          pp_t_unary_output_conjunction_logical])
  have E_domain:
      "Elem (pp_t_probe_boolean_expr_den E)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
  proof -
    have E_valid: "pp_t_probe_boolean_expr_valid E"
      using PPProbeBooleanConj.prems by simp
    show ?thesis
      by (rule pp_t_probe_boolean_expr_den_in_domain[OF E_valid])
  qed
  have F_domain:
      "Elem (pp_t_probe_boolean_expr_den F)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
  proof -
    have F_valid: "pp_t_probe_boolean_expr_valid F"
      using PPProbeBooleanConj.prems by simp
    show ?thesis
      by (rule pp_t_probe_boolean_expr_den_in_domain[OF F_valid])
  qed
  have first:
      "pp_t_cone_rel pp_t_boolean_probe_transformer_type s
        (pp_t_unary_output_conjunction_den
          \<acute> pp_t_probe_boolean_expr_den E)
        (pp_t_unary_output_conjunction_den
          \<acute> pp_t_probe_boolean_expr_den E)"
    using conjunction E_domain PPProbeBooleanConj
    by simp
  show ?case
    using first F_domain PPProbeBooleanConj
    by simp
qed

definition pp_t_probe_boolean_representatives :: "ZF set" where
  "pp_t_probe_boolean_representatives =
    pp_t_probe_boolean_expr_den `
      {E. pp_t_probe_boolean_expr_valid E}"

lemma pp_t_probe_boolean_representatives_countable:
  "countable pp_t_probe_boolean_representatives"
  unfolding pp_t_probe_boolean_representatives_def
  by simp

lemma pp_t_probe_boolean_representative_in_domain:
  assumes "d \<in> pp_t_probe_boolean_representatives"
  shows "Elem d (pp_t_domain pp_t_boolean_probe_unary_type)"
  using assms pp_t_probe_boolean_expr_den_in_domain
  unfolding pp_t_probe_boolean_representatives_def
  by blast

lemma pp_t_probe_boolean_representative_cone_natural:
  assumes "d \<in> pp_t_probe_boolean_representatives"
  shows "pp_t_cone_rel pp_t_boolean_probe_unary_type s d d"
  using assms pp_t_probe_boolean_expr_den_cone_natural
  unfolding pp_t_probe_boolean_representatives_def
  by blast

lemma pp_t_probe_boolean_representative_equivariant:
  assumes "d \<in> pp_t_probe_boolean_representatives"
  shows "pp_b_equivariant (pp_b_operator_of d)"
  by (rule pp_t_cone_rel_operator_implies_equivariant)
    (rule
      pp_t_probe_boolean_representative_cone_natural[
        OF assms])

definition pp_t_probe_boolean_stock ::
    "bool list \<Rightarrow> ZF \<Rightarrow> bool"
where
  "pp_t_probe_boolean_stock w X \<longleftrightarrow>
    Elem X (pp_t_domain pp_t_boolean_probe_unary_type)
    \<and>
    (\<exists>d \<in> pp_t_probe_boolean_representatives.
      pp_t_eqv pp_t_boolean_probe_unary_type w X d)"

lemma pp_t_probe_boolean_stock_admissible:
  "pp_t_predicate_admissible pp_t_boolean_probe_unary_type
    pp_t_probe_boolean_stock"
proof (unfold pp_t_predicate_admissible_def, intro allI impI)
  fix w X Y v
  assume X: "Elem X (pp_t_domain pp_t_boolean_probe_unary_type)"
    and Y: "Elem Y (pp_t_domain pp_t_boolean_probe_unary_type)"
    and XY: "pp_t_eqv pp_t_boolean_probe_unary_type w X Y"
    and wv: "prefix w v"
  have XYv:
      "pp_t_eqv pp_t_boolean_probe_unary_type v X Y"
    by (rule pp_t_eqv_persistent[OF XY wv])
  have YXv:
      "pp_t_eqv pp_t_boolean_probe_unary_type v Y X"
    by (rule pp_t_eqv_symmetric[OF X Y XYv])
  show "pp_t_probe_boolean_stock v X =
      pp_t_probe_boolean_stock v Y"
  proof
    assume stock: "pp_t_probe_boolean_stock v X"
    then obtain d where
        d: "d \<in> pp_t_probe_boolean_representatives"
      and Xd:
        "pp_t_eqv pp_t_boolean_probe_unary_type v X d"
      unfolding pp_t_probe_boolean_stock_def by blast
    have d_domain:
        "Elem d (pp_t_domain pp_t_boolean_probe_unary_type)"
      by (rule
        pp_t_probe_boolean_representative_in_domain[OF d])
    have Yd:
        "pp_t_eqv pp_t_boolean_probe_unary_type v Y d"
      by (rule pp_t_eqv_transitive[
        OF Y X d_domain YXv Xd])
    show "pp_t_probe_boolean_stock v Y"
      unfolding pp_t_probe_boolean_stock_def
      using Y d Yd by blast
  next
    assume stock: "pp_t_probe_boolean_stock v Y"
    then obtain d where
        d: "d \<in> pp_t_probe_boolean_representatives"
      and Yd:
        "pp_t_eqv pp_t_boolean_probe_unary_type v Y d"
      unfolding pp_t_probe_boolean_stock_def by blast
    have d_domain:
        "Elem d (pp_t_domain pp_t_boolean_probe_unary_type)"
      by (rule
        pp_t_probe_boolean_representative_in_domain[OF d])
    have Xd:
        "pp_t_eqv pp_t_boolean_probe_unary_type v X d"
      by (rule pp_t_eqv_transitive[
        OF X Y d_domain XYv Yd])
    show "pp_t_probe_boolean_stock v X"
      unfolding pp_t_probe_boolean_stock_def
      using X d Xd by blast
  qed
qed

lemma pp_t_probe_boolean_stock_cone_iff:
  assumes X: "Elem X (pp_t_domain pp_t_boolean_probe_unary_type)"
    and Y: "Elem Y (pp_t_domain pp_t_boolean_probe_unary_type)"
    and XY:
      "pp_t_cone_rel pp_t_boolean_probe_unary_type s X Y"
  shows "pp_t_probe_boolean_stock (s @ u) X
    \<longleftrightarrow> pp_t_probe_boolean_stock u Y"
proof -
  have representative:
      "\<And>d.
        d \<in> pp_t_probe_boolean_representatives
        \<Longrightarrow>
        (pp_t_eqv pp_t_boolean_probe_unary_type (s @ u) X d
        \<longleftrightarrow>
        pp_t_eqv pp_t_boolean_probe_unary_type u Y d)"
  proof -
    fix d
    assume d: "d \<in> pp_t_probe_boolean_representatives"
    have d_domain:
        "Elem d (pp_t_domain pp_t_boolean_probe_unary_type)"
      by (rule
        pp_t_probe_boolean_representative_in_domain[OF d])
    have d_cone:
        "pp_t_cone_rel pp_t_boolean_probe_unary_type s d d"
      by (rule
        pp_t_probe_boolean_representative_cone_natural[OF d])
    show "pp_t_eqv pp_t_boolean_probe_unary_type (s @ u) X d
        \<longleftrightarrow>
        pp_t_eqv pp_t_boolean_probe_unary_type u Y d"
      using UnconditionalCone.pp_t_cone_rel_eqv_iff[
        OF X Y d_domain d_domain XY d_cone, of u] .
  qed
  show ?thesis
    unfolding pp_t_probe_boolean_stock_def
    using X Y representative by blast
qed

lemma pp_t_closed_logical_stock_subset_probe_boolean_stock:
  assumes
    "pp_t_closed_logical_stock
      pp_t_boolean_probe_unary_type w X"
  shows "pp_t_probe_boolean_stock w X"
proof -
  obtain M where
      typed: "[] \<turnstile> M : pp_t_boolean_probe_unary_type"
    and logical: "pp_logical_vocabulary M"
    and XM:
      "pp_t_eqv pp_t_boolean_probe_unary_type w
        X (pp_t_closed_den M)"
    using assms
    unfolding pp_t_closed_logical_stock_def by blast
  have X:
      "Elem X (pp_t_domain pp_t_boolean_probe_unary_type)"
    using assms
    unfolding pp_t_closed_logical_stock_def by blast
  have representative:
      "pp_t_closed_den M
        \<in> pp_t_probe_boolean_representatives"
  proof -
    have valid:
        "pp_t_probe_boolean_expr_valid
          (PPProbeBooleanLogical M)"
      using typed logical by simp
    have member:
        "PPProbeBooleanLogical M
          \<in> {E. pp_t_probe_boolean_expr_valid E}"
      using valid by simp
    have image:
        "pp_t_probe_boolean_expr_den
            (PPProbeBooleanLogical M)
          \<in> pp_t_probe_boolean_expr_den `
            {E. pp_t_probe_boolean_expr_valid E}"
      by (rule imageI[OF member])
    show ?thesis
      unfolding pp_t_probe_boolean_representatives_def
      using image by simp
  qed
  show ?thesis
    unfolding pp_t_probe_boolean_stock_def
    using X representative XM by blast
qed

lemma pp_t_symmetrized_probe_in_probe_boolean_stock:
  "pp_t_probe_boolean_stock w
    pp_t_symmetrized_closed_stock_probe"
proof -
  have representative:
      "pp_t_symmetrized_closed_stock_probe
        \<in> pp_t_probe_boolean_representatives"
  proof -
    have valid:
        "pp_t_probe_boolean_expr_valid
          PPProbeBooleanGenerator"
      by simp
    have member:
        "PPProbeBooleanGenerator
          \<in> {E. pp_t_probe_boolean_expr_valid E}"
      using valid by simp
    have image:
        "pp_t_probe_boolean_expr_den
            PPProbeBooleanGenerator
          \<in> pp_t_probe_boolean_expr_den `
            {E. pp_t_probe_boolean_expr_valid E}"
      by (rule imageI[OF member])
    show ?thesis
      unfolding pp_t_probe_boolean_representatives_def
      using image by simp
  qed
  show ?thesis
    unfolding pp_t_probe_boolean_stock_def
    using pp_t_symmetrized_closed_stock_probe_in_domain
      representative
      pp_t_eqv_reflexive[
        OF pp_t_symmetrized_closed_stock_probe_in_domain]
    by blast
qed

lemma pp_t_probe_boolean_stock_represented:
  assumes stock: "pp_t_probe_boolean_stock w X"
  obtains E where
    "pp_t_probe_boolean_expr_valid E"
    "pp_t_eqv pp_t_boolean_probe_unary_type w X
      (pp_t_probe_boolean_expr_den E)"
  using stock
  unfolding pp_t_probe_boolean_stock_def
    pp_t_probe_boolean_representatives_def
  by (blast intro: that)

lemma pp_t_probe_boolean_stock_output_negation_closed:
  assumes stock: "pp_t_probe_boolean_stock w X"
  shows "pp_t_probe_boolean_stock w
    (pp_t_closed_den pp_t_unary_output_negator \<acute> X)"
proof -
  obtain E where
      valid: "pp_t_probe_boolean_expr_valid E"
    and represented:
      "pp_t_eqv pp_t_boolean_probe_unary_type w X
        (pp_t_probe_boolean_expr_den E)"
    using stock
    by (rule pp_t_probe_boolean_stock_represented)
  have X:
      "Elem X (pp_t_domain pp_t_boolean_probe_unary_type)"
    using stock
    unfolding pp_t_probe_boolean_stock_def by blast
  have d:
      "Elem (pp_t_probe_boolean_expr_den E)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
    by (rule pp_t_probe_boolean_expr_den_in_domain[OF valid])
  have N:
      "Elem (pp_t_closed_den pp_t_unary_output_negator)
        (pp_t_domain pp_t_boolean_probe_transformer_type)"
    by (rule pp_t_closed_den_in_domain)
      (rule pp_t_unary_output_negator_typed)
  have NN:
      "pp_t_eqv pp_t_boolean_probe_transformer_type w
        (pp_t_closed_den pp_t_unary_output_negator)
        (pp_t_closed_den pp_t_unary_output_negator)"
    by (rule pp_t_eqv_reflexive[OF N])
  have result:
      "pp_t_eqv pp_t_boolean_probe_unary_type w
        (pp_t_closed_den pp_t_unary_output_negator \<acute> X)
        (pp_t_closed_den pp_t_unary_output_negator
          \<acute> pp_t_probe_boolean_expr_den E)"
    by (rule pp_t_app_respects[OF NN X d represented])
  have result_domain:
      "Elem
        (pp_t_closed_den pp_t_unary_output_negator \<acute> X)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
    by (rule pp_t_app_closed[OF N X])
  have representative:
      "pp_t_closed_den pp_t_unary_output_negator
          \<acute> pp_t_probe_boolean_expr_den E
        \<in> pp_t_probe_boolean_representatives"
  proof -
    have neg_valid:
        "pp_t_probe_boolean_expr_valid
          (PPProbeBooleanNeg E)"
      using valid by simp
    have member:
        "PPProbeBooleanNeg E
          \<in> {F. pp_t_probe_boolean_expr_valid F}"
      using neg_valid by simp
    have image:
        "pp_t_probe_boolean_expr_den (PPProbeBooleanNeg E)
          \<in> pp_t_probe_boolean_expr_den `
            {F. pp_t_probe_boolean_expr_valid F}"
      by (rule imageI[OF member])
    show ?thesis
      using image
      unfolding pp_t_probe_boolean_representatives_def
      by simp
  qed
  show ?thesis
    unfolding pp_t_probe_boolean_stock_def
    using result_domain representative result by blast
qed

lemma pp_t_probe_boolean_stock_output_conjunction_closed:
  assumes X_stock: "pp_t_probe_boolean_stock w X"
    and Y_stock: "pp_t_probe_boolean_stock w Y"
  shows "pp_t_probe_boolean_stock w
    ((pp_t_unary_output_conjunction_den \<acute> X) \<acute> Y)"
proof -
  obtain E where
      E_valid: "pp_t_probe_boolean_expr_valid E"
    and X_E:
      "pp_t_eqv pp_t_boolean_probe_unary_type w X
        (pp_t_probe_boolean_expr_den E)"
    using X_stock
    by (rule pp_t_probe_boolean_stock_represented)
  obtain F where
      F_valid: "pp_t_probe_boolean_expr_valid F"
    and Y_F:
      "pp_t_eqv pp_t_boolean_probe_unary_type w Y
        (pp_t_probe_boolean_expr_den F)"
    using Y_stock
    by (rule pp_t_probe_boolean_stock_represented)
  have X:
      "Elem X (pp_t_domain pp_t_boolean_probe_unary_type)"
    using X_stock
    unfolding pp_t_probe_boolean_stock_def by blast
  have Y:
      "Elem Y (pp_t_domain pp_t_boolean_probe_unary_type)"
    using Y_stock
    unfolding pp_t_probe_boolean_stock_def by blast
  have d:
      "Elem (pp_t_probe_boolean_expr_den E)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
    by (rule pp_t_probe_boolean_expr_den_in_domain[OF E_valid])
  have e:
      "Elem (pp_t_probe_boolean_expr_den F)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
    by (rule pp_t_probe_boolean_expr_den_in_domain[OF F_valid])
  have K:
      "Elem pp_t_unary_output_conjunction_den
        (pp_t_domain pp_t_boolean_probe_builder_type)"
    by (rule pp_t_unary_output_conjunction_den_in_domain)
  have KK:
      "pp_t_eqv pp_t_boolean_probe_builder_type w
        pp_t_unary_output_conjunction_den
        pp_t_unary_output_conjunction_den"
    by (rule pp_t_eqv_reflexive[OF K])
  have first:
      "pp_t_eqv pp_t_boolean_probe_transformer_type w
        (pp_t_unary_output_conjunction_den \<acute> X)
        (pp_t_unary_output_conjunction_den
          \<acute> pp_t_probe_boolean_expr_den E)"
    by (rule pp_t_app_respects[OF KK X d X_E])
  have KX:
      "Elem (pp_t_unary_output_conjunction_den \<acute> X)
        (pp_t_domain pp_t_boolean_probe_transformer_type)"
    by (rule pp_t_app_closed[OF K X])
  have Kd:
      "Elem
        (pp_t_unary_output_conjunction_den
          \<acute> pp_t_probe_boolean_expr_den E)
        (pp_t_domain pp_t_boolean_probe_transformer_type)"
    by (rule pp_t_app_closed[OF K d])
  have result:
      "pp_t_eqv pp_t_boolean_probe_unary_type w
        ((pp_t_unary_output_conjunction_den \<acute> X) \<acute> Y)
        ((pp_t_unary_output_conjunction_den
          \<acute> pp_t_probe_boolean_expr_den E)
          \<acute> pp_t_probe_boolean_expr_den F)"
    by (rule pp_t_app_respects[OF first Y e Y_F])
  have result_domain:
      "Elem
        ((pp_t_unary_output_conjunction_den \<acute> X) \<acute> Y)
        (pp_t_domain pp_t_boolean_probe_unary_type)"
    by (rule pp_t_app_closed[OF KX Y])
  have representative:
      "(pp_t_unary_output_conjunction_den
          \<acute> pp_t_probe_boolean_expr_den E)
          \<acute> pp_t_probe_boolean_expr_den F
        \<in> pp_t_probe_boolean_representatives"
  proof -
    have conjunct_valid:
        "pp_t_probe_boolean_expr_valid
          (PPProbeBooleanConj E F)"
      using E_valid F_valid by simp
    have member:
        "PPProbeBooleanConj E F
          \<in> {G. pp_t_probe_boolean_expr_valid G}"
      using conjunct_valid by simp
    have image:
        "pp_t_probe_boolean_expr_den (PPProbeBooleanConj E F)
          \<in> pp_t_probe_boolean_expr_den `
            {G. pp_t_probe_boolean_expr_valid G}"
      by (rule imageI[OF member])
    show ?thesis
      using image
      unfolding pp_t_probe_boolean_representatives_def
      by simp
  qed
  show ?thesis
    unfolding pp_t_probe_boolean_stock_def
    using result_domain representative result by blast
qed

lemma pp_t_probe_boolean_stock_root_represented:
  assumes X: "Elem X (pp_t_domain pp_t_boolean_probe_unary_type)"
    and stock: "pp_t_probe_boolean_stock [] X"
  obtains d where
    "d \<in> pp_t_probe_boolean_representatives"
    "pp_t_eqv pp_t_boolean_probe_unary_type [] X d"
  using stock
  unfolding pp_t_probe_boolean_stock_def
  by (blast intro: that)

theorem pp_t_probe_boolean_stock_root_seed_exists:
  "\<exists>r. Elem r (pp_t_domain Prop)
    \<and> pp_t_unary_recombines_at
      pp_t_probe_boolean_stock r []"
proof (rule
    pp_t_countably_represented_unary_stock_root_seed_exists[
      where D=pp_t_probe_boolean_representatives])
  show "countable pp_t_probe_boolean_representatives"
    by (rule pp_t_probe_boolean_representatives_countable)
  show "\<And>d.
      d \<in> pp_t_probe_boolean_representatives
      \<Longrightarrow>
      Elem d (pp_t_domain pp_t_one_context_unary_type)"
    by (rule pp_t_probe_boolean_representative_in_domain)
  show "\<And>d.
      d \<in> pp_t_probe_boolean_representatives
      \<Longrightarrow> pp_b_equivariant (pp_b_operator_of d)"
    by (rule pp_t_probe_boolean_representative_equivariant)
  show "\<And>X.
      Elem X (pp_t_domain pp_t_one_context_unary_type)
      \<Longrightarrow> pp_t_probe_boolean_stock [] X
      \<Longrightarrow>
      \<exists>d \<in> pp_t_probe_boolean_representatives.
        pp_t_eqv pp_t_one_context_unary_type [] X d"
    using pp_t_probe_boolean_stock_root_represented
    by blast
qed

definition pp_t_probe_boolean_stock_root_seed :: ZF where
  "pp_t_probe_boolean_stock_root_seed =
    (SOME r. Elem r (pp_t_domain Prop)
      \<and> pp_t_unary_recombines_at
        pp_t_probe_boolean_stock r [])"

lemma pp_t_probe_boolean_stock_root_seed_spec:
  "Elem pp_t_probe_boolean_stock_root_seed
      (pp_t_domain Prop)
    \<and> pp_t_unary_recombines_at
      pp_t_probe_boolean_stock
      pp_t_probe_boolean_stock_root_seed []"
  unfolding pp_t_probe_boolean_stock_root_seed_def
  using someI_ex[OF pp_t_probe_boolean_stock_root_seed_exists] .

definition pp_t_probe_boolean_stock_seed_at ::
    "bool list \<Rightarrow> ZF"
where
  "pp_t_probe_boolean_stock_seed_at w =
    pp_t_cone_lift w pp_t_probe_boolean_stock_root_seed"

lemma pp_t_probe_boolean_stock_seed_at_in_domain:
  "Elem (pp_t_probe_boolean_stock_seed_at w)
    (pp_t_domain Prop)"
  unfolding pp_t_probe_boolean_stock_seed_at_def
  by (rule pp_t_cone_lift_in_domain)

theorem pp_t_probe_boolean_stock_seed_recombines_at_every_world:
  "pp_t_unary_recombines_at
    pp_t_probe_boolean_stock
    (pp_t_probe_boolean_stock_seed_at w) w"
  unfolding pp_t_probe_boolean_stock_seed_at_def
  by (rule
    pp_t_unary_stock_root_recombination_transports_to_cone[
      OF
        pp_t_probe_boolean_stock_root_seed_spec[THEN conjunct1]
        pp_t_probe_boolean_stock_root_seed_spec[THEN conjunct2]
        pp_t_probe_boolean_stock_cone_iff])

end
