theory Bacon_PP_Decided_Realization
  imports Bacon_PP_Attainment_Failure
begin

section \<open>Can the counterexample be realized over a seed?\<close>

text \<open>
  \<open>Bacon_PP_Attainment_Failure\<close> exhibits a domain over which the non-contingency body
  defeats attainment, and leaves open whether such a domain can arise as the Henkin
  closure of a language over a seed.  This theory records what stands in the way, and
  the news for realization is bad.

  Two facts.  First, \<open>pp_decided X\<close> is always closed under going deeper, so the sets
  of deciding worlds are up-sets and the counterexample needs a strictly decreasing
  sequence of them with empty intersection.  Second --- and this is the obstruction ---
  if the domain contains even one proposition that is decided \emph{nowhere}, the
  intersection is already empty at that single element, attainment holds, and the
  counterexample collapses.

  Nowhere-decided propositions are not exotic.  Every parity proposition is one:
  its views are only itself and its complement, and neither is \<open>{}\<close> or \<open>UNIV\<close>.  So
  any domain containing a parity proposition attains, and the domain generated by
  \<open>C\<^sub>n = {w. length w \<le> n}\<close> works only because every one of its members is decided
  somewhere.

  Realizing the counterexample over a seed therefore requires a seed-generated domain
  containing no nowhere-decided proposition at all.  That is already a strong demand
  on a domain built from a generic witness.

  The last section sharpens this into what looks decisive.  Decidedness passes through
  the Boolean connectives and the modality, so a world deciding a generating family
  decides everything it generates.  Hence a domain generated by \emph{finitely many}
  propositions always attains, at its generators.  In particular the Boolean-and-modal
  closure of a single seed always attains, and the attaining element is the seed
  itself.  So a realization cannot come from that closure: it needs identity, the
  quantifiers or \<open>Pure\<close> to manufacture infinitely many propositions no finite
  subfamily of which decides the rest.
\<close>

subsection \<open>Deciding worlds form an up-set\<close>

lemma pp_view_empty[simp]:
  "pp_view k {} = {}"
  by (simp add: pp_view_def)

lemma pp_view_UNIV[simp]:
  "pp_view k UNIV = UNIV"
  by (simp add: pp_view_def)

theorem pp_decided_deeper:
  assumes "i \<in> pp_decided X"
  shows "k @ i \<in> pp_decided X"
proof -
  have compose: "pp_view (k @ i) X = pp_view k (pp_view i X)"
    by (simp add: pp_view_compose)
  from assms consider
      (top) "pp_view i X = UNIV" | (bot) "pp_view i X = {}"
    by (auto simp: pp_decided_iff)
  then show ?thesis
  proof cases
    case top
    then have "pp_view (k @ i) X = UNIV"
      using compose by simp
    then show ?thesis by (simp add: pp_decided_iff)
  next
    case bot
    then have "pp_view (k @ i) X = {}"
      using compose by simp
    then show ?thesis by (simp add: pp_decided_iff)
  qed
qed

corollary pp_decided_accessible:
  assumes "i \<in> pp_decided X" and "pp_accessible i j"
  shows "j \<in> pp_decided X"
  using assms pp_decided_deeper
  unfolding pp_accessible_def by blast

subsection \<open>One nowhere-decided proposition restores attainment\<close>

definition pp_nowhere_decided :: "pp_sem_prop \<Rightarrow> bool" where
  "pp_nowhere_decided X \<longleftrightarrow> pp_decided X = {}"

theorem pp_nowhere_decided_gives_attainment:
  assumes mem: "B \<in> U"
    and nowhere: "pp_nowhere_decided B"
  shows "pp_finitely_attained U pp_decided"
proof -
  have "pp_forall_over {B} pp_decided = pp_decided B"
    by (auto simp: pp_forall_over_iff)
  then have "pp_forall_over {B} pp_decided = {}"
    using nowhere by (simp add: pp_nowhere_decided_def)
  then have "pp_forall_over {B} pp_decided \<subseteq> pp_forall_over U pp_decided"
    by simp
  then show ?thesis
    unfolding pp_finitely_attained_def
    using mem by blast
qed

subsection \<open>Parity propositions are nowhere decided\<close>

lemma pp_parity_root[simp]:
  "[] \<in> pp_parity E"
  by (simp add: pp_parity_def)

lemma pp_parity_not_UNIV:
  assumes "k \<in> E"
  shows "pp_parity E \<noteq> UNIV"
proof -
  have "[k] \<notin> pp_parity E"
    using assms by (simp add: pp_parity_def)
  then show ?thesis by blast
qed

lemma pp_parity_not_empty:
  "pp_parity E \<noteq> {}"
  using pp_parity_root by blast

theorem pp_parity_nowhere_decided:
  assumes nonempty: "E \<noteq> {}"
  shows "pp_nowhere_decided (pp_parity E)"
proof -
  obtain k where k: "k \<in> E" using nonempty by blast
  have not_top: "pp_parity E \<noteq> UNIV"
    using k by (rule pp_parity_not_UNIV)
  have not_bot: "pp_parity E \<noteq> {}"
    by (rule pp_parity_not_empty)
  have views: "pp_view i (pp_parity E) \<noteq> UNIV \<and>
      pp_view i (pp_parity E) \<noteq> {}" for i
  proof (cases "even (length (filter (\<lambda>k. k \<in> E) i))")
    case True
    then have "pp_view i (pp_parity E) = pp_parity E"
      by (simp add: pp_parity_view)
    then show ?thesis using not_top not_bot by simp
  next
    case False
    then have "pp_view i (pp_parity E) = - pp_parity E"
      by (simp add: pp_parity_view)
    moreover have "- pp_parity E \<noteq> UNIV"
      using not_bot by blast
    moreover have "- pp_parity E \<noteq> {}"
      using not_top by blast
    ultimately show ?thesis by simp
  qed
  show ?thesis
    unfolding pp_nowhere_decided_def
    using views by (auto simp: pp_decided_iff)
qed

corollary pp_domain_with_parity_attains:
  assumes mem: "pp_parity E \<in> U"
    and nonempty: "E \<noteq> {}"
  shows "pp_finitely_attained U pp_decided"
  using mem pp_parity_nowhere_decided[OF nonempty]
  by (rule pp_nowhere_decided_gives_attainment)

subsection \<open>Why the counterexample domain escapes\<close>

text \<open>
  The domain of \<open>Bacon_PP_Attainment_Failure\<close> avoids the obstruction only because
  every one of its generators is decided somewhere: \<open>C\<^sub>n\<close> is decided at every world
  deeper than \<open>n\<close>.  So it contains no nowhere-decided proposition, and that is exactly
  what lets the intersection escape every finite part.
\<close>

theorem pp_shortprop_not_nowhere_decided:
  "\<not> pp_nowhere_decided (pp_shortprop n)"
proof -
  have "pp_zeros (Suc n) \<in> pp_decided (pp_shortprop n)"
    by (simp add: pp_decided_shortprop)
  then show ?thesis
    unfolding pp_nowhere_decided_def by blast
qed

subsection \<open>Finitely generated domains always attain\<close>

text \<open>
  A sharper obstruction, and the decisive one for a single seed.  Decidedness passes
  through the Boolean connectives and the modality, so a world deciding a generating
  family decides everything the family generates.  If the domain is generated by
  \emph{finitely many} propositions, the generators themselves already attain the
  intersection, and the counterexample cannot arise.
\<close>

inductive_set pp_bmclosure :: "pp_sem_prop set \<Rightarrow> pp_sem_prop set"
  for G :: "pp_sem_prop set" where
    bm_base: "X \<in> G \<Longrightarrow> X \<in> pp_bmclosure G"
  | bm_compl: "X \<in> pp_bmclosure G \<Longrightarrow> - X \<in> pp_bmclosure G"
  | bm_inter: "X \<in> pp_bmclosure G \<Longrightarrow> Y \<in> pp_bmclosure G \<Longrightarrow>
      X \<inter> Y \<in> pp_bmclosure G"
  | bm_box: "X \<in> pp_bmclosure G \<Longrightarrow>
      pp_sem_box X \<in> pp_bmclosure G"

theorem pp_decided_bmclosure:
  assumes X: "X \<in> pp_bmclosure G"
    and decides: "\<And>g. g \<in> G \<Longrightarrow> i \<in> pp_decided g"
  shows "i \<in> pp_decided X"
  using X
proof (induct rule: pp_bmclosure.induct)
  case (bm_base X)
  then show ?case by (rule decides)
next
  case (bm_compl X)
  then show ?case by simp
next
  case (bm_inter X Y)
  then show ?case by (simp add: pp_decided_Int)
next
  case (bm_box X)
  then show ?case by (simp add: pp_decided_box)
qed

theorem pp_bmclosure_attains:
  assumes G_fin: "finite G"
    and G_sub: "G \<subseteq> U"
    and U_sub: "U \<subseteq> pp_bmclosure G"
  shows "pp_finitely_attained U pp_decided"
proof -
  have "pp_forall_over G pp_decided \<subseteq> pp_forall_over U pp_decided"
  proof
    fix i
    assume i: "i \<in> pp_forall_over G pp_decided"
    have decides: "i \<in> pp_decided g" if "g \<in> G" for g
      using i that by (simp add: pp_forall_over_iff)
    show "i \<in> pp_forall_over U pp_decided"
      unfolding pp_forall_over_iff
    proof (intro ballI)
      fix X
      assume "X \<in> U"
      then have "X \<in> pp_bmclosure G" using U_sub by blast
      then show "i \<in> pp_decided X"
        using decides by (rule pp_decided_bmclosure)
    qed
  qed
  then show ?thesis
    unfolding pp_finitely_attained_def
    using G_fin G_sub by blast
qed

corollary pp_single_seed_closure_attains:
  assumes seed: "r \<in> U"
    and generated: "U \<subseteq> pp_bmclosure {r}"
  shows "pp_finitely_attained U pp_decided"
proof (rule pp_bmclosure_attains)
  show "finite {r}" by simp
  show "{r} \<subseteq> U" using seed by simp
  show "U \<subseteq> pp_bmclosure {r}" by (rule generated)
qed

text \<open>
  So the Boolean-and-modal closure of a single seed \emph{always} attains, and the
  attaining element is the seed itself.  A realization of the counterexample therefore
  cannot come from that closure alone: it needs the rest of the language --- identity,
  the quantifiers, \<open>Pure\<close> --- to manufacture infinitely many propositions no finite
  subfamily of which decides the rest.
\<close>

subsection \<open>The exact obligation for a realization\<close>

text \<open>
  Putting the two together: a seed-generated domain realizes the counterexample only
  if none of its members is nowhere decided.  Contrapositively, exhibiting a single
  nowhere-decided proposition in the domain kills the realization.
\<close>

theorem pp_realization_requires_no_nowhere_decided:
  assumes "\<not> pp_finitely_attained U pp_decided"
  shows "\<forall>B \<in> U. \<not> pp_nowhere_decided B"
  using assms pp_nowhere_decided_gives_attainment by blast

text \<open>
  This is a real constraint on any seed-generated domain, and it is the reason to be
  pessimistic about realization.  A domain built from a generic witness is closed
  under the Boolean connectives and the modality, and it has to contain a contingent
  seed; the demand is that no combination of these ever produces a proposition whose
  every view is properly between \<open>{}\<close> and \<open>UNIV\<close>.  Parity propositions show that such
  propositions exist in abundance in the ambient model; the open question is only
  whether the particular seed-generated subdomain can avoid all of them.

  Note the asymmetry this creates.  To \emph{refute} realization it suffices to show
  that some seed-generated domain member is nowhere decided --- a single witness.  To
  \emph{establish} realization one must rule that out for every member, which is a
  universal claim about the whole closure.  The burden is therefore on realization,
  and the counterexample of the previous theory should for now be read as a statement
  about Boolean-and-box-closed domains only, exactly as it is stated there.
\<close>

end
